### ISSUE TITLE
Line numbers reversed

### ISSUE THREAD

**Issue by alexmironof** [onivim/oni2#113]
![screenshot from 2019-03-04 12-31-40](https://user-images.githubusercontent.com/6573628/53723845-add6a100-3e79-11e9-8e15-714ab041d16e.png)

I guess there is no need to calculate relative line number here [src/editor/UI/EditorSurface.re#L107](https://github.com/onivim/oni2/blob/master/src/editor/UI/EditorSurface.re#L107) and use just `bufferLine`

**Comment by CrossR** [comment]
I think the issue here is more that the configuration option hasn't been hooked up yet (since we've not got a fully complete configuration story yet!) so the option is hard-coded to relative line number, since I assume that is what @bryphe uses most!

We should have the option to chose between `On`/`Off`/`Relative` once that is fully hooked up, just like with standard neovim.

**Comment by alexmironof** [comment]
Oh I see, so this is a feature and not a bug :sweat_smile: I didn't realize that moving cursor around also changes line numbers and it works as expected

**Comment by CrossR** [comment]
There is an article on it here : https://jeffkreeftmeijer.com/vim-number/

Broadly:
 - Number is just number of the line.
 - Relative shows you the relative difference from your cursor line, so you can do motions more easily.
      - Ie you know that the line you are looking at is 15 up, without having to calculate it.

I do agree it can be confusing though! The default will be swapped to Number, I assume it was left as relative as that is the slightly more complicated case to code up vs just numbers.
