### ISSUE TITLE
macOS cmd-tab icon looks non-retina

### ISSUE THREAD

**Issue by jaredly** [onivim/oni2#1166]
<img width="444" alt="Screen Shot 2020-01-04 at 4 06 16 PM" src="https://user-images.githubusercontent.com/112170/71772684-63480a00-2f0c-11ea-9d22-2dfc744fb29b.png">

this is on master, running with `esy run`

**Comment by leematos** [comment]
I dug into this one, and it looks like the logo is being rendered based on the logo.png:

`
[DEBUG]    +0ms Revery.Core.Window : Loading icon from: /Users/lbot/Development/onivim/oni2/_release/./Onivim2.app/Contents/MacOS/logo.png`

This is where it happens in revery: https://github.com/revery-ui/revery/blob/2f6f985927dcdf362c2ac1d915c7f752278485dd/src/Core/Window.re#L428

The logo.png file is currently 64x64, so that explains that.

The outstanding questions are:

- Can/should we be using the icon set here on Mac?
- If not, is there commonplace wisdom on cross-platform app icon sizing?

We can make logo.png 1024x1024, but I don't know what kind of effects that would have on windows/linux.

I think this classifies as a revery bug, as the framework should handle that abstraction imo.

**Comment by mr-sour** [comment]
![image](https://user-images.githubusercontent.com/2181180/82620800-08533e80-9b9f-11ea-9e7e-6d196511acd5.png)
I assume this is the same bug but it looks low res if you have large dock icons to. I vote to just up it to 256x256 and let the operating system scale it down if need be. It looks like linux and mac-os can support pgn icons upto 512x512 but windows becomes has the lowest resolution at 256x256. A more ideal solution would be assets for each build using icns ico and pgn with max support size but for a cross platform pgn it looks like 256 is the best bet.
