### ISSUE TITLE
UI scaling -- probably revery related

### ISSUE THREAD

**Issue by jasin** [onivim/oni2#1189]
UI scaling on windows is horrible out of the box! But I thought according to the documentation on the site that since windows 8.1+ oni2 uses the display device scaling, yet when changing the scale factor in windows for the display device oni2 is unaffected. Was I missing the point?

> Windows: On 8.1+, we use the 'scale factor' of the display device.

I was hoping that this would be a work around, but not that I can see. I'll be glad to see this fixed

**Comment by CrossR** [comment]
Upstream issue here: https://github.com/revery-ui/revery/issues/598

What is perhaps happening is that you are changing between 125/150/175/200% scaling, but in all cases we treat that as scaling by 2 in revery to my knowledge, since we can't do that fractional scaling yet. Skia integration is ongoing but should fix this.

**Comment by volllly** [comment]
I think this is fixed now.

**Comment by bryphe** [comment]
We should be picking up the scale factor on startup - but we're not handling the case where it changes while the app is running. Need to see if there is a way we can get this from SDL2, or if we need a hook into the Win32 api

**Comment by bryphe** [comment]
Should be fixed with https://github.com/revery-ui/revery/issues/598 now
