### ISSUE TITLE
Lack of font fallback for missing unicode glyphs

### ISSUE THREAD

**Issue by advpetc** [onivim/oni2#1293]
I have a small issue with rendering unicode symbol:
![Screen Shot 2020-02-04 at 6 34 14 PM](https://user-images.githubusercontent.com/15725244/73797301-ac92b000-477d-11ea-8cd9-6776fe60f7e5.png)
Check on the third line of the screenshot, and you will find question mark for that.
![Screen Shot 2020-02-04 at 6 38 42 PM](https://user-images.githubusercontent.com/15725244/73797347-c6cc8e00-477d-11ea-9c52-9357a5f70ee6.png)
Using ga command I can check the unicode value is 8209.

Is there any quick fix for this?

My environment: MacOS with 10.15.3 Catalina.

Thanks.

**Comment by glennsl** [comment]
I'm assuming you're using the default font, but this will depend on the font you're using. If the font doesn't contain a glyph for a certain code point it will look something like this. So you could try setting a different font in the configuration.

I'm not sure if this should be considered an enhancement or a bug as very few fonts support the entire unicode codespace. I've marked it as an enhancement for now, but I also know the current default font hasn't been given a lot of consideration and is likely to change anyway when we get around to consider it properly.

**Comment by Apostolique** [comment]
If a glyph isn't found, I think a backup font should be used.

**Comment by bryphe** [comment]
Yes, this is one thing we're missing right now - 'font fallback' - since most fonts don't cover Unicode codespace, browsers and platform tech stacks usually fall-back to other fonts to render the characters. There's a great article on the challenges / complexity of this: [Font fallback deep dive](https://raphlinus.github.io/rust/skribo/text/2019/04/04/font-fallback.html)

Skia offers an API for this: https://api.skia.org/classSkFontMgr.html#aedf1cc4052672d3ba2f787012679aa55 , where we can query based on a font, language, and a character, to find the best system fallback font matching the unicode character.

We'd need to update our shaping algorithm such that, when we find 'holes' that aren't covered by the existing font, to pickup a fallback font and render those holes. We assume right now that the result of text shaping is a single font - we'd need to change that assumption so that the shape result can be list of `(typeface, glyphIds)`, representing each of the runs, and evaluate how to most efficiently cache the fallback fonts.

**Comment by kmyk** [comment]
Please increase the priority of this issue.
For those who use non-ASCII letters, this is a very serious bug, not a small issue.

For example, a normal text written in Japanese (copied from https://ja.wikipedia.org/wiki/%E8%B1%86%E8%85%90) is entirely broken as follows:

<img width="601" alt="Annotation 2020-03-15 095325" src="https://user-images.githubusercontent.com/2203128/76693101-27b38400-66a3-11ea-8be6-2ee2469450b1.png">

Expected:

<img width="785" alt="Annotation 2020-03-15 095330" src="https://user-images.githubusercontent.com/2203128/76693100-23876680-66a3-11ea-9f1b-85a280b34037.png">


Environment:

- Onivim 2 (0.3.0), downloaded from https://www.onivim.io/early-access-portal
- Windows 10 (Version 1903, OS Build 18362.720))

**Comment by glennsl** [comment]
@kmyk Does it not work to set `editor.fontFamily` to a font that supports Japanese characters?

**Comment by CrossR** [comment]
From my testing on the same page, If I set a Japanese compatible font, then I get normal rendering. I tested with `MS Gothic` on Windows.

Thats a simple way of getting around the issue of no fallback for now, and I assume works for every language.

**Comment by kmyk** [comment]
@glennsl Thank you! It works. But I have the next problem.
Characters are rendered, but they are overlapped. The widths seems not correct. (By the way, should I make a different issue for this?)

![Screenshot from 2020-03-16 20-32-00](https://user-images.githubusercontent.com/2203128/76754424-73f6e500-67c5-11ea-8fd0-f20f09ea863a.png)

environment: Ubuntu 18.04.4 LTS (Bionic Beaver)
(I cannot access my Windows environment now)

---

- I tested with Noto Sans, IPA Gothic, and VL Gothic. All fonts have the same problem.
 To test, download [NotoSansCJKjp-hinted.zip](https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip) from https://www.google.com/get/noto/help/cjk/ and set `"editor.fontFamily": "/path/to/NotoSansMonoCJKjp-Regular.otf"`. (Setting `"editor.config": "Noto Sans Mono CJK JP"` or `"editor.fontfamily": "/usr/share/fonts/opentype/noto/notosanscjk-regular.ttc"` installed via `apt install fonts-noto-cjk` doesn't work.)
- Test file: [tofu.md](https://github.com/onivim/oni2/files/4337959/tofu.md.txt)
- I found a related issue: #868

**Comment by glennsl** [comment]
@kmyk That seems like #1364, and if so is specific to Linux. Try setting `"editor.fontSmoothing": "subpixel-antialiased"`.

Regardless of whether or not this works, it might be a good idea to create a separate issue for it. If it doesn't work the underlying issue is certainly not the same as this, which is about lack of fallback. But even if it does work, we need to figure out a better default. This shouldn't require manual configuration.

**Comment by kmyk** [comment]
@glennsl The setting didn't solve the font overlapping problem.
I made the new issue https://github.com/onivim/oni2/issues/1475 for this.

**Comment by geohuz** [comment]
I'm still having font displaying issue with the following setting:
```
  "editor.fontFamily": "NotoSansCJK.ttc",
  "editor.detectIndentation": true,
  "editor.fontSmoothing": "subpixel-antialiased",
```

here is the problem of chinese font rendering:
<img width="498" alt="Screen Shot 2020-06-27 at 12 28 32 AM" src="https://user-images.githubusercontent.com/730770/85879567-30bd0100-b80d-11ea-827f-cac2d500423a.png">

and font overlapping even in english characters:

<img width="376" alt="Screen Shot 2020-06-27 at 12 30 17 AM" src="https://user-images.githubusercontent.com/730770/85879712-63ff9000-b80d-11ea-9b48-ffe5c78f0c63.png">

I really hope this critical issue can be fixed as I just purchased editor and can't use it for daily work.

**Comment by bryphe** [comment]
Hi @geohuz ,

Sorry that this issue is still around and blocking using it for your work. @zbaylin and I will be working on this shortly (proper font-fallback behavior). It's definitely on our radar - we'll keep you posted.

The font-sizing behavior / overlapping is very strange - just to get a bit more info, what sort of device are you using? A MacBook, Mac Mini? And are you using a high-dpi / retina display?

**Comment by geohuz** [comment]
Hi @bryphe,

Thanks for your prompt reply! I'm using the MacBook Pro (16-inch, 2019), with retina display. I'm explored the issue further last night, I found if I use a font package with everything include (mono CJK and other encodings) then all the characters rendering correctly without overlapping here and there. One of such package is losevka: https://typeof.net/Iosevka/ , I'm now running the build process to build the fonts.

**Comment by geohuz** [comment]
After hours of processing fonts under project "Sarasa-Gothic" - https://github.com/be5invis/Sarasa-Gothic , everything works happily!

<img width="446" alt="Screen Shot 2020-06-27 at 6 26 14 PM" src="https://user-images.githubusercontent.com/730770/85920119-b12e4100-b8a3-11ea-8038-ac8a7260f3fb.png">

there is no font overlapping, no missing blank blocks, and with nice font's alignment and size!

**Comment by bryphe** [comment]
Looks like with @zbaylin 's work on [font-fallback in Revery](https://zachbayl.in/blog/font-fallback-revery.html) (and merging into Onivim here: https://github.com/onivim/oni2/pull/2113) - the file is now rendering as expected:

![image](https://user-images.githubusercontent.com/13532591/87858264-8868fc80-c8e1-11ea-9689-c50b271e355f.png)

Should be fixed now - but please open a new issue if you are still seeing any font-fallback issues 👍

**Comment by geohuz** [comment]
I downloaded latest version (2.0.3.0) from early access portal(paied user), the font-fallback worked in most case but failed for some characters, and only on text inputting. For example, the chinese character "者" (zhe) can be rendered without any problem but weird things happens when typing such character,  it becomes 
<img width="146" alt="Screen Shot 2020-08-02 at 11 56 30 AM" src="https://user-images.githubusercontent.com/730770/89115146-36b29b80-d4b7-11ea-933a-4162d3a60146.png">

and there is another (zhe) "着", being rendered upon input as:
<img width="136" alt="Screen Shot 2020-08-02 at 11 57 48 AM" src="https://user-images.githubusercontent.com/730770/89115153-66fa3a00-d4b7-11ea-803b-6d4cc2eee666.png">

most other characters from (zhe) are rendered ok, I can imagine there are other special cases like this.

**Comment by bryphe** [comment]
Thanks for testing the change @geohuz ! This looks similar to #1293 (except for CJK, vs cyrillic characters)

**Comment by geohuz** [comment]
@bryphe I'm writing to confirm the issue has gone after downloading the latest version, thanks for all the hard work!
