### ISSUE TITLE
going to insert mode sometimes inserts a 'j'

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#1305]
I find this bug quite hard to reproduce as it appears intermittently. Often when I go into insert mode it also inserts a 'j', this happens not only when I press `i` but also when I press `o`. 
Not sure if this is a known issue, if not let me know if you need some more data to help track it down. 
(OS macOS catalina)

**Comment by CrossR** [comment]
Would be useful to know your Oni2 config if that has anything custom in it.

Since its intermittent, if possible you could set the `ONI2_DEBUG` and `ONI2_LOG_FILE` variables and log out to a file whilst you use Oni2 normally, then hopefully catch it occurring. You'd then be able to see the log for that event. (https://onivim.github.io/docs/using-onivim/command-line#logging)

**Comment by yunti** [comment]
I can't repeat this anymore so best to close. Thanks for the offer to help.
