### ISSUE TITLE
Unable to focus search results of 'Find in files'

### ISSUE THREAD

**Issue by olliebaum** [onivim/oni2#1329]
After entering a search query and hitting enter in the 'Find in files' search field, the field maintains focus instead of giving focus to the results, so trying to navigate the results with `j`/`k` just continues typing in the search field. In fact I'm completely unable to focus the results by keyboard shortcut or clicking, am I missing something?

**Comment by glennsl** [comment]
No, you're not missing anything. It just hasn't been implemented yet. It is high on the todo list though :)

**Comment by olliebaum** [comment]
Cool, thanks. Is there anywhere we can see the priority list of what’s being worked on + coming next?

**Comment by glennsl** [comment]
Not really. We mostly guide our own work and don't have any overall methodology or queues we work from. But there are some sources you can use to get an idea of the bigger picture:

- The most important one is [the timeline on the website](https://www.onivim.io/), since those are commitments with actual deadlines. SO far we've done a lot of work on SCM and Skia, but the remaining points are chugging along as well.
- We also have [a number of projects/boards](https://github.com/onivim/oni2/projects) we use to keep track of the progress on bigger chunks of work. We could definitely become better at using these though.
- There are also [some meta issues](https://github.com/onivim/oni2/issues?q=is%3Aopen+is%3Aissue+label%3Ameta) we use to discuss and track bugger features.
- Otherwise we try to prioritize issues by the number of upvotes they have. But we usually try to look at and work on these as part of a bigger picture instead of picking them directly out of the list.

I hope that helps at least a little bit.

**Comment by bryphe** [comment]
This should be fixed now - you can use `Control-W`, `Control-J` (move down a window) to jump down to the results list:
![search-results](https://user-images.githubusercontent.com/13532591/98189921-cd359500-1eca-11eb-8742-7bc1f809e67a.gif)
