### ISSUE TITLE
Sneak: Navigation not working between two split editor tabs

### ISSUE THREAD

**Issue by Blackhawk-TA** [onivim/oni2#1394]
When there are two files open in editor split view it is not possible to navigate between them using sneak shortcuts. The focus stays in the currently active editor window.
This problem occurs on horizontal and vertical split view.

![grafik](https://user-images.githubusercontent.com/36313322/75634733-8b07d580-5c10-11ea-9c2a-8d591a6d0518.png)

In this screenshot the focus is on the editor window with the shortcut 'AM'. When pressing 'BK' the focus should switch to the corresponding file. This does not happen, the focus stays on the file with the 'AM' shortcut.

Tested systems:
- Windows 10 1909
- macOS 10.15.3 (iMac late 2013)

**Comment by shulhi** [comment]
I took a look at this and the bug is due to incorrect(?) state in SneakStore,

https://github.com/onivim/oni2/blob/cc79c6febdaa74eb4e5fc9dd41669715f6ffd9ba/src/Store/SneakStore.re#L45-L51

When sneak action is executed, the active buffer state is still pointing to the original buffer (left split assuming where are moving from `AM` to `BK`) 

https://github.com/onivim/oni2/blob/cc79c6febdaa74eb4e5fc9dd41669715f6ffd9ba/src/Store/VimStoreConnector.re#L737-L743

Thus when `synchronizeEditorEffect` is called above, the id still refers to the id of the left split so it remains in the same editor.

I was wondering why using the mouse click works, both sneak action and actual click called the same `onClick` function? I am still investigating this but any pointers are appreciated.

Note: If anyone else wants to work on this it is fine too, I'm just doing this in my free time which is not much :smile:

**Comment by shulhi** [comment]
Apparent, the active window is set on mouse down from editor group view, https://github.com/onivim/oni2/blob/cc79c6febdaa74eb4e5fc9dd41669715f6ffd9ba/src/UI/EditorGroupView.re#L267-L272

@glennsl is there any particular reason that this state must be set during mouse down event?

**Comment by glennsl** [comment]
Nice find @shulhi!

Looks like it's to be able to catch clicks on both tabs, editors and all the chrome around it in one place. This is all very old and imperative unfortunately, so I think the easiest way to fix this is would be to just call `GlobalContext.current().setActiveWindow` on tab click as well. Hopefully that'll work.

Ideally we`d like to use the `Focus` infrastructure for this, so that instead of setting the active editor and active editor group separately and have some complicated logic to keep it synchronized, you'd just set one value, the focus, and derive the active editor and editor group from that. Might be tricky to do though, particularly because of the interaction with libvim, and hopefully it isn't necessary to fix this.
