### ISSUE TITLE
Terminal fails to load default shell

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#1403]
MacOS Catalina
Nightly build, commit: a5e6fb52,

When launched the terminal loads bash, rather than the default shell (for me this is fish).

(Fish will now load if I enter the fish command).

**Comment by glennsl** [comment]
We actually talked about this yesterday. For most Unixes it's easy enough to get the user shell since it's stored in plain text in `/etc/passwd`, and there's even an OCaml API for it in the `Unix` module. But of course macOS is different (because Apple), and we're not sure how to best do this programatically yet. It's possible to use the `dscl` command to retrieve it. not very elegant, but worst case that should work.

**Comment by kinglouie** [comment]
Shouldn't the default shell be set in $SHELL env var? at least on macOS when I run the oni2 terminal it runs bash and when I run `echo $SHELL` it returns the zsh path which is my default shell.

**Comment by yunti** [comment]
Yup and for me `echo $SHELL` returns the correct path for fish too. However it looks like it isn't being picked up by Onivim2

**Comment by glennsl** [comment]
As I understand, `$SHELL` isn't entirely reliable. But perhaps it's OK as a fallback mechanism on macOS. It would certainly be faster than calling out to `dscl`.
