### ISSUE TITLE
terminal display problem

### ISSUE THREAD

**Issue by pkariz** [onivim/oni2#1559]
I'm using debian 10 with i3 window manager.
[video of the problem](https://easyupload.io/aexon0)
if it's unclear what i write...
```
cd haskell<enter>
cd ..<enter>
cd haskell22<backspace><backspace><enter>
```
then just move between normal and insert mode in terminal.
Later i played with it again to generate the log, don't remember exactly what i've typed in the terminal.
[here is the log](https://easyupload.io/xd5eow)

Just for the info, i'm using [pure](https://github.com/sindresorhus/pure)

**Comment by bryphe** [comment]
Looks related to #1456

**Comment by bryphe** [comment]
There were actually two issues here - one was a bug in our harfbuzz shaping logic that was fixed here: https://github.com/revery-ui/revery/pull/934 - this could cause characters to be 'doubled up' sometimes as shown in that video due to a bug in our shaping code.

The second issue is that we don't have font-fallback properly implemented (which is required to get a nice looking prompt from pure) - will use #1456 to track that.
