### ISSUE TITLE
Memory leak in Syntax Highlight Service

### ISSUE THREAD

**Issue by CrossR** [onivim/oni2#1613]
There has been 2-3 reports on Discord with people having memory leaks that seem to be coming from the syntax highlight process specifically.

To my knowledge, this has been reported on Linux only so far, and can happen both when the editor is running, and also on close (this one may have changed since #1488, the last report of this was before then).

The process basically uses all available memory on the machine: 

I'll link this issue in Discord and hopefully we can get some logs from someone, as I've been unable to repro on my machine (source build, tar.gz, appimage).

**Comment by necabo** [comment]
So I just compiled 8ba63de2 to ensure my repro still works. Running Arch Linux on 5.6.3-arch1-1.

It's quite simple and 100% reproducible for me. Sending a SIGTERM to Oni2 in order to close it causes the highlight service to go beserk until the oom killer finally gets rid of it. 2-3 minutes after closing Oni2 that way, it looks something like this: 
![oni2](https://user-images.githubusercontent.com/23185845/79273333-209ab400-7ea3-11ea-85a7-17f1a7169fd7.png)

This issue doesn't occur when using `:q` to quit.

**Comment by CrossR** [comment]
With the changes that were made (#1619, #1621) above and the fact there has been no other reporting of this recently, I'll close this out.

If someone is still experiencing this, we can re-open.
