### ISSUE TITLE
Keybinding in Quick Open / Command Palette

### ISSUE THREAD

**Issue by alarsyo** [onivim/oni2#1624]
Hi,

I'd like to bind `<C-j>` to `list.focusDown` (and `<C-k>` to `list.focusUp`) in the command palette / quick open menu. I couldn't find a `when` clause that works, though (I thought `menuFocus` was for this).

(I basically want to rebind `<C-p>` / `<C-n>` in the quick open menu)

Is this not possible yet?

**Comment by CrossR** [comment]
You should be able to do:

```json
[
  { "key": "<c-j>", "command": "list.focusDown", "when": "listFocus || textInputFocus" },
  { "key": "<c-k>", "command": "list.focusUp", "when": "listFocus || textInputFocus" },
]
```

Since the docs aren't really complete yet, it can sometimes be easier to look over the code for this sort of stuff. I.e. most of the default bindings live here: https://github.com/onivim/oni2/blob/master/src/Store/KeyBindingsStoreConnector.re.

Anything used in there should be usable in your config as well.
Hope that helps!

**Comment by CrossR** [comment]
It looks like we swapped from menuFocus to listFocus at some point, and the docs weren't updated...I can't see when/why the change was made though, or if its just that the docs are wrong.

**Comment by alarsyo** [comment]
Awesome, that's what I needed. Thanks!

**Comment by CrossR** [comment]
Great! I've updated our general keybinding issue to mention that we need to get the docs up to date (and keep them up to date once stuff is added), so I'll close this out.
