### ISSUE TITLE
splits and :tabedit do not work nicely with each other / do not have vim behavior

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1644]
It looks like :tabedit and the splits (:split and :vsplit) do not work so nicely together.

If I am right:

- in vim, :tabedit opens tabs, and then within the tab it is possible to open as many splits as wanted. By doing gt or gT, one moves between tabs, each containing all the corresponding splits. This is convenient, as I can have a tab for fixing something, another for working on another issue, etc.

By contrast here:

- using gt/T for moving between tabs move only the tab in the current split. I.e., we have a split of tabs, rather than a tab of splits.

**Comment by CrossR** [comment]
This comes down to the difference between an Oni2 "tab" and a vim tab.

An Oni2 "tab" is actually just a buffer shown in a tab, so the tab related commands do not work with it, since its not a real vim tab.

There is a feature request over here for the normal vim behaviour (the behaviour we have here is more VSCode like) and we intend to support the normal vim behaviour as well : https://github.com/onivim/oni2/issues/592

If its a feature you want, make sure to hit the thumbs up, since we use that to prioritise issues over others.

Since this is a known issue because of https://github.com/onivim/oni2/issues/592, I'll close this out.
