### ISSUE TITLE
native support chinese charactor

### ISSUE THREAD

**Issue by broven** [onivim/oni2#1666]
I had read the issue about fix chinese charactor problem
but can't oni2 just support chinese charactor? It's confused to rookie
#1091

**Comment by glennsl** [comment]
It should, but there's probably bugs. Seeing as none of us developers can read Chinese, it's often hard to tell exactly what's right or wrong. So if something doesn't work, we rely on those experiencing it to accurately describe and help us troubleshoot the issues.

In #1091 specifically, the problem is likely that we don't support font fallback. But if you configure a font that has all the needed glyphs, and therefore doesn't need to rely on a fallback mechanism, it should work. That's my hypothesis and what I suggested there at least, but since they've not reported back I don't actually know whether it works. Not hearing back might be a sign that it did though.

By the way, you can also comment on existing issues. There's no need to create new issues for questions relating to existing ones.
