### ISSUE TITLE
Buffers may represent cyrillic characters incorrectly

### ISSUE THREAD

**Issue by avimmer** [onivim/oni2#1720]
Onivim 2 0.4.0 `ea560d1d`
`:set enc?` is `utf-8`
When inserting the `р` character onivim represents it as `рþX`.

**Comment by bryphe** [comment]
Another manifestation of this looks like typing `者` - it ends up with similar problematic additional characters. Likely a similar root cause as the cyrillic `р`

**Comment by bryphe** [comment]
This was interesting to investigate because it only happens for a subset of Unicode UTF-8 characters... It turns out, there is a bug in our input handling - in particular, when we replace term codes: https://github.com/onivim/libvim/blob/796a77496c4c3fb341de9e42363bc2c6d1433fe1/src/libvim.c#L212

That `replace_termcodes` function has special handling for byte `0x80`/`128` - this is treated as a special key (https://github.com/onivim/libvim/blob/7b10e4c7011388e7db1bddffc128f52bb47a21a6/src/keymap.h#L29) and expanded to a 3-byte sequence, which corrupts the UTF-8 character.

The assumption was that input could just be passed to `replace_termcodes`, but we'll need to differentiate between 'text' that shouldn't be expanded, and strings that should be (ie, like `<LEFT>`, `<C-V>`, etc)
