### ISSUE TITLE
Scrolling is laggy on Windows

### ISSUE THREAD

**Issue by Muream** [onivim/oni2#174]
As discussed on the discord, I'm noticing some lag while scrolling down in Oni2. Here's a video showing neovim-qt (left) and oni2 (right) scrolling on the same file side by side: https://youtu.be/b8Eml4qTIHI

Here's the log with the minimap activated: [minimap_log.txt](https://github.com/onivim/oni2/files/2987747/minimap_log.txt)
And here it is without the minimap: [no_minimap_log.txt](https://github.com/onivim/oni2/files/2987748/no_minimap_log.txt)
In both cases the scrolling part is the the first indented stuff starting from the bottom.
The indented lines at the top happened when I cd-ed and opened the file.

The issue seemed less present without the minimap but It still felt a bit laggy.

For reference, I have a GTX 1080 w/ 8Gigs of vram, a ryzen 2500 and 16Gigs of ram and this was tested on Windows 10 launching everything from `cmd.exe` as admin.

If you need any more info/data/testing from me just ask!

Edit: I just built Oni2 on my Linux partition, same machine and I don't have any stuttering while scrolling

**Comment by bryphe** [comment]
@Muream investigated it this a bit on Discord - we found that turning off "Thread optimization" in the NVIDIA control panel fixed the stuttering. 

Fine workaround for now, however, that isn't a maintainable fix - it can improve performance for other apps / games so leaving it as 'auto' is the best approach.

I saw various threads about this setting causing problems:
- https://www.reddit.com/r/battlefield_live/comments/6vqg8j/effect_of_nvidia_threaded_optimization_on_fps/
- https://forums.x-plane.org/index.php?/forums/topic/86354-micro-stutter-with-newer-nvidia-gpus-culprit-and-cure-finally-found/
- https://stackoverflow.com/questions/36959508/nvidia-graphics-driver-causing-noticeable-frame-stuttering
- https://steamcommunity.com/app/379720/discussions/0/358417461603470028/

For other NVIDIA users who hit this, here's the setting you can try to see if it fixes it:
![image](https://user-images.githubusercontent.com/13532591/54726099-c52ab500-4b2e-11e9-9bbe-c5b8617b5f80.png)

To fix this, there are a few different avenues I'm looking at:

- __ANGLE__ - Instead of using OpenGL directly, we could use [ANGLE](hub.com/Microsoft/angle), which translates OpenGL ES to DirectX. From reading, it seems that the 'Thread Optimization' issues are specific to OpenGL, so this could fix it - but would need to test.

- Validate we aren't doing anything crazy in 'user-space' with our OpenGL calls to exacerbate this. We do have a high draw call count at the moment, since we don't do very much batching (either for text, or things like the minimap squares)

- Create an NVIDIA profile on install and disable the 'Thread Optimization' setting via that profile. This means we can disable the setting just for Onivim 2 w/o impacting other apps/games.

**Comment by Muream** [comment]
I just realized that you can manually add a custom profile to turn off threaded optimization just for Oni2:  
Once you're in the screenshot that Bryphe took, go to Program Settings tab and click `add` while Oni2 is running, select Oni2.exe turn off threaded optimization, apply and restart Oni2.

That's definitely a workaround but that'll work until the issue gets properly resolved.

**Comment by Muream** [comment]
Also @bryphe your ANGLE link is broken, I'm guessing this is what you wanted to link:
https://github.com/Microsoft/angle

**Comment by bryphe** [comment]
With our latest build - where there is no 'async' handling of input, the performance seems much better for scrolling now on Windows, and I don't see the issue with the Thread Optimization setting.

However - we do need to optimize our rendering pipeline. It's not currently the bottleneck (the textmate highlighting is, right now) - but it will be soon. We need to improve the way we batch rendering both text and other primitives (like the minimap - we shouldn't have an individual draw call for each rectangle).
