### ISSUE TITLE
Windows 10 Pro - No usable display

### ISSUE THREAD

**Issue by dlbradford** [onivim/oni2#1809]
Hi,
Please see screencap. 

My Windows 10 Pro is running as a VM in Virtualbox 6.1 if that matters.

![Onivim2-Windows10-2020-05-23_084154](https://user-images.githubusercontent.com/72617/82731049-27062200-9cd2-11ea-9be8-98523e1d51f8.png)

**Comment by bryphe** [comment]
Thanks @dlbradford for logging the issue! Currently, the editor relies on OpenGL 4+ on Windows - which [doesn't seem to be well-supported in VirtualBox](https://forums.virtualbox.org/viewtopic.php?f=2&t=82614) There might be a way to configure VirtualBox for it, though.

We're also looking at supporting DirectX render strategy (via `ANGLE`), which it does seem like virtualbox has better support for (and more broadly, better Windows support in general).

**Comment by dlbradford** [comment]
@bryphe, thank you for the reply and likely explanation. I will mess about with it to see if I can sort it out re OpenGL 4+ in VirtualBox.

**Comment by bryphe** [comment]
Hi @dlbradford - this should be fixed now w/ latest builds, as we use ANGLE as the renderer strategy on Windows (which uses the better-supported D3D instead of OpenGL). I've tested on Hyper-V and Parallels which both had similar issues.

Will close as fixed with #2283 , but please let me know if you still have issues opening Onivim
