### ISSUE TITLE
Quickopen crashes if working dir is changed

### ISSUE THREAD

**Issue by Samonitari** [onivim/oni2#188]
If you issue a `chdir` command to somewhere other than oni2 root, and then use `<C-P>` to launch quickopen, Oni2 crashes.

Both master, and #184 (ripgrep, yay!) merged into master reports:
>Fatal error: exception Oni_Neovim__NeovimApi.RequestFailed("Request timed out: nvim_command (XX)")

Maybe some paths are handled as relative in the source, that should be absolute?

**Comment by Akin909** [comment]
@Samonitari :+1: , yeah seems neovim is hanging on the request probably as you say a path we're handing it somewhere probably gets this turned around I've been working around there so will take a look when I get a chance

**Comment by Akin909** [comment]
I've looked into this a bit and some of the functionality has changed, the quickOpen no longer crashes but no results are displayed. This is because the nvim api request fails (as discussed) because we use `getcwd`, but if a user is in a `[No Name]` buffer or a buffer that doesn't exists anywhere the call seems to not be resolved.

In terminal nvim though this isn't the case, but for some reason in this context the api call fails. If the user is in a named buffer though this does not happen.
I'm not sure why the behaviour would be any different as even calling the `nvim_call_function('getcwd', [])` returns the correct value in terminal nvim

**Comment by Samonitari** [comment]
Interesting...

I tried, and yes it works: if I am in a named buffer, AND the current working dir is in sync with the buffer, quickopen works.

I probably should open a separate bug about tab management, but I thought you are aware, and oni2 is quite in alpha stage. But I'll bring it up anyway:
Opening new tabs breaks the tab switching: `gt` or `gT` is rapsodic, however you can switch by clicking more reliably. It is quite flimsy, I did not manage the figure out the "logic" of the bug, sometimes the order is wrong, sometimes a tabs is unreachable, or one `gt` is always swallowed when cycling.

**Comment by Akin909** [comment]
@Samonitari yes the tabs and buffer state is a different question we haven't entirely solved. Oni2 is currently defaulting to showing `buffers` so tabs and tab commands won't work as expected. We haven't yet decided on a way for handling both simultaneously or if we would do that at all. To get consistent behavior you have to use `e filename`, and other buffer commands

**Comment by bryphe** [comment]
This should be fixed now with the latest `reason-libvim` - and our explorer even updates with `:cd` with #404 . If there are additional issues not addressed by these changes - feel free to open a new issue 👍
