### ISSUE TITLE
Double clicking on the window title bar crashes oni2 on macOS

### ISSUE THREAD

**Issue by ianwhite** [onivim/oni2#1910]
On macOS Catalina, Oni2 v0.4.0

When double clicking on the window title bar (to make the window fullscreen) Oni2 crashes, and produces an almost empty crashlog file in the working directory (attached)

[onivim2-crash.log](https://github.com/onivim/oni2/files/4757790/onivim2-crash.log)

Clicking the fullscreen button (the rightmost of the three buttons on the left of the window title bar) works as expected as does not lead to a crash

**Comment by bryphe** [comment]
Thanks for logging the issue, @ianwhite !

Indeed, I can repro as well on Catalina. It looks like we're crashing here:
https://github.com/onivim/oni2/blob/d773a256d5e06327e2abadf68df5462aa0a754c3/src/Store/TitleStoreConnector.re#L112

On double-click, we're checking the default action (it turns out you can override the titlebar behavior). However, we're assuming it's always set - when it isn't, we crash - the `End_of_File` in that log is because we're trying to read from `stdout`, but the `defaults` command doesn't send anything to `stdout` to fix.

Should be a straightforward fix - in the case where a default isn't available, we'll default to maximize.
