### ISSUE TITLE
[Idea] extensions installing sources

### ISSUE THREAD

**Issue by Miziak** [onivim/oni2#1932]
As it is mentioned here https://github.com/onivim/oni2/issues/1018 there is licencing problem with installing extensions from https://marketplace.visualstudio.com/ alternative is http://open-vsx.org/ but it not contain all of extensions.  But there is one page containing all vscode extensions there is github...

As we steal some ideas from vim community maybe we steal another - plugin installing. Installing and updating extensions not contained in http://open-vsx.org/ may be painful so idea semi-solve legal problems.

So we can build something like https://github.com/junegunn/vim-plug but in oni and for vscode extensions with gui.

Details:
1. In extensions tab can be button called "Add extension source" -> clicked, show dialog with input to paste extension gh link
2. After add source oni pull info about extension from gh(I assume it is legal) and put it into install possible
3. Happy user have nice installing experience for non-open-vsx extensions and autoupdate

**Comment by bryphe** [comment]
Thanks @Miziak for opening the issue! Indeed, [open-vsx](https://open-vsx.org/) looks really promising. Our extension installation story is not ideal at the moment - seems like this could solve a lot of problems for us.

My plan is to have an interface for it, in Onivim, so that we can install these open extensions directly. Essentially a new UI (a custom buffer, like `oni://install-extension`) to search, download, and install. It'd also be our source of our truth for updating - 

And in cases where a VSCode isn't available there - it looks like we can help out by publishing extensions. For example, the ctags extension in #1905 would be one we could help publish.

Hoping we can have this in for our July release!

**Comment by bryphe** [comment]
I'll close this out, since we now have an extension management story for the open-vsx plugins (although, we still need update - will track that in #1018 ). Thanks for the ideas and brainstorming!
