### ISSUE TITLE
Startup is slow on OSX after update

### ISSUE THREAD

**Issue by dansisan** [onivim/oni2#1983]
I'm on OSX version 10.14.6. After upgrading (for the first time) on Saturday, opening an empty text file takes around 10 seconds, and the CPU spikes (due to kernel_task). I upgraded again today and the behavior is the same. The first time I installed, the weekend before last, this problem didn't exist. 

I'm not sure if this is a recently introduced problem or if there's something about how I upgraded (I simply followed the installation instructions: opened the .dmg, moved it to the Applications folder, and said I wanted to replace the old version).

I'm opening the file using the command line `oni2 empty_file.txt`. When I open Oni without an argument or by double clicking on the icon in the Applications folder it opens my entire home folder, and takes a similarly long time. I wonder if the entire home folder is being opened on every startup, even when a single file argument is passed? (No else seems to be complaining about this, and my home directory is in fact ridiculously large.)

**Comment by CrossR** [comment]
If you open a different folder, i.e. `oni2 ~/git/someProject`, is it just as slow? The folder you use is also persisted, so perhaps there is just an issue in the home folder?

If not, then it must be something else.

**Comment by dansisan** [comment]
@CrossR Actually, that opens quickly. So why does passing a file instead of a folder behave differently? It shouldn't open a folder to open a single file.

You're saying there's a default folder persisted that's always opened? How can I change that default folder?

**Comment by CrossR** [comment]
When you open a folder, Oni2 will actually swap to that folder (if you open a file, it should also open that folder too, so `~/git/someFolder/README.md` should open `~/git/someFolder`). Then, when you swap folders (either at launch or with `:cd`) we save that folder to a config file to be used later.

If you launch Oni2 without any arguments, we then use that saved folder. It sounds like there is something on the blocking path, assumedly in the explorer, that is causing this issue when you open Oni2 in a folder with lots of files, like your home folder. There is limits on how deep we recurse etc, but maybe there is missing limits on the numbers of files we should look at on open (or delay all of that until the UI is up and do it in the background then).

For now, since you've moved out of the home folder, when you launch from the dock it should default to the folder you used last. Obviously the real fix here is to find that bottleneck and fix it.

**Comment by dansisan** [comment]
What does "open a folder" entail? You're saying when I open a single file on the command line, by design Oni2 is not simply opening that single file? 

Just discovered a related problem that's even worse: if I try to save a file in my home directory, Oni2 consumes CPU indefinitely and becomes unresponsive.

I also discovered if I open a much smaller subfolder (4 files, ~200kB total), it can still take 3-5 seconds to open Oni2 from the command line.

Lastly, if I open Oni2 when there is already a window open (e.g. running `oni .` twice in a row in the same folder without closing the first window, the second opening is much faster.

**Comment by CrossR** [comment]
>What does "open a folder" entail? You're saying when I open a single file on the command line, by design Oni2 is not simply opening that single file?

When I say "open a folder" I just mean the explorer will swap to that folder. That way, when you do `:e` or `Ctrl-Shift-P` etc, you are working from that folder. Vim doesn't do this by default, but there are plugins for it. We don't do anything to the files in there etc, its just a `cd` into the folder.

It sounds like there is something weird happening on startup for you. Could you run with the `--debug -f` flags, to get some debug information out?
