### ISSUE TITLE
Env variable not passed to vscode extension

### ISSUE THREAD

**Issue by nolondil** [onivim/oni2#1985]
I'm trying time to time to see if [metals](https://marketplace.visualstudio.com/items?itemName=scalameta.metals#overview) vs-code extension works with Onivim2.

`JAVA_HOME` variable is not passed to the metals extension in Onivim

<img width="944" alt="Screenshot 2020-06-23 at 01 21 29" src="https://user-images.githubusercontent.com/2758059/85344563-55089d00-b4f0-11ea-95a3-ae0fa17d80c4.png">

But it seems to be available to Onivim

<img width="407" alt="Screenshot 2020-06-23 at 01 25 55" src="https://user-images.githubusercontent.com/2758059/85344635-841f0e80-b4f0-11ea-9505-e752be473ee9.png">

I would expect `JAVA_HOME` to be available for the extension.

build: 3c720f0e
system: macOS 10.15

**Comment by bryphe** [comment]
Hi @nolondil - this should be fixed now in the latest builds - I was using this scala extension: https://marketplace.visualstudio.com/items?itemName=scalameta.metals

The error message was a bit misleading; it was actually failing here: 
https://github.com/scalameta/metals-vscode/blob/3d288d23fc6602dd7531bd9ac6aa2d6eeef2533a/src/extension.ts#L100

due to Onivim not passing in the configuration context (it's expected that `metals.javaHome` should at least be populated with `null`) - this was fixed in https://github.com/onivim/oni2/pull/1967

**Comment by bryphe** [comment]
I'll close this out as fixed in #1967 , but please let me know if you're still seeing the issue

**Comment by nolondil** [comment]
@bryphe I confirm that it start the metals server without any configuration done now. Really nice 👍 and LSP functionality are correctly picked up.
