### ISSUE TITLE
Fails to load in Win7

### ISSUE THREAD

**Issue by pd-giz-dave** [onivim/oni2#2036]
I tried to run this in a Windows 7 VirtualBox vm which fails. Running it with depends gives this error:

LoadLibraryW("SHCORE.DLL") called from "SDL2.DLL" at address 0x00000000042EEDC8.
LoadLibraryW("SHCORE.DLL") returned NULL. Error: The specified module could not be found (126).

This is not available in Win7. Is it your intention to support Win7?

**Comment by CrossR** [comment]
Usually this is due to older version OpenGL version, something like issue #1842, where we need 4+. Getting some logs out with `-f --debug` would help track that down further perhaps, or running `--checkhealth`.

Windows 7 is officially end of life (since Feb), so we aren't aiming to support it directly so there may be some issues, and some features (well, in Revery at least) won't work in Windows 7 since there isn't the ability in Win 7 for it. That said, this specific issue seems more like a VM specific issue, rather than Win 7 directly.

**Comment by bryphe** [comment]
Thanks for logging the issue and the details, @pd-giz-dave !

I suspect it must be an issue here: https://github.com/revery-ui/revery/blob/dcfe586c83739812c320a93202245b2fd086243d/src/reason-sdl2/sdl2_wrapper.cpp#L364

We're assuming `SHCORE.DLL` is available (but it's actually only available on Win8+). We could wrap that in a version check - but there maybe other downstream failures past that.

We weren't planning on supporting Windows 7 because it's EOL - but there have been a few requests for it. If there are any other users stuck on Windows 7 - 👍  this issue so we can prioritize it. 

I need to dig up a Windows 7 environment too.

I think the VM issue is probably this one: https://github.com/onivim/oni2/issues/994 - the VMs tend to have issues with the OpenGL support. We need to either switch to DirectX (better supported) or a software rendering strategy (supported regardless of hardware): https://github.com/onivim/oni2/issues/1588

**Comment by bryphe** [comment]
Since Windows 7 was EOL almost a year ago (Jan 14th 2020) - and haven't heard any other requests for support -  no plans to support it. 

Updated our [system requirements](https://onivim.github.io/docs/getting-started/installation#system-requirements) to reflect that:
![image](https://user-images.githubusercontent.com/13532591/100813059-528d6600-33f3-11eb-9bb4-74cc7a7f80b6.png)
