### ISSUE TITLE
Syntax highlighting missing in Signature help

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#2051]
Using latest nightly:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/1826271/86371342-ac3d0900-bc78-11ea-9222-d8e4e02a28a7.png">

vs all working well in hover (not sure how both of them appeared at the same time):
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1826271/86371433-c4ad2380-bc78-11ea-8e3a-6836018efd0f.png">

**Comment by bryphe** [comment]
@zbaylin - I'm wondering for this, do we just need to port over the `defaultLanguage` like we do for the Hover overlay?

```
    let defaultLanguage =
      Exthost.LanguageInfo.getLanguageFromBuffer(languageInfo, buffer);
    let hoverMarkdown = (~markdown) =>
      Oni_Components.Markdown.make(
        ~colorTheme,
        ~tokenTheme,
        ~languageInfo,
...
```

https://github.com/onivim/oni2/blob/1786185adfd25ce5ccc5e88c896ae530dd9ce097/src/Feature/Hover/Feature_Hover.re#L265

in here:

https://github.com/onivim/oni2/blob/1786185adfd25ce5ccc5e88c896ae530dd9ce097/src/Feature/SignatureHelp/Feature_SignatureHelp.re#L463 ?

Might be a quick fix!

**Comment by zbaylin** [comment]
I'm actually not sure if Signature Help is supposed to have highlights or not. In VSCode it doesn't seem to highlight the parameter hints:

![image](https://user-images.githubusercontent.com/4527949/88226095-91d3cb00-cc39-11ea-985a-cc652071597e.png)

I think since the signature help often has non-code elements (i.e. descriptions of parameters) it's not highlighted by default -- I'll look into this a little more.

**Comment by bryphe** [comment]
Oh, right - I was thinking of the markdown below in @yunti 's screenshot:

![image](https://user-images.githubusercontent.com/13532591/88228746-77dbbd80-cc24-11ea-81d4-cfef8fdaaa72.png)

(rather than the signature help, itself)

**Comment by zbaylin** [comment]
Ah 🤦‍♂️ my bad haha! That should be an easy fix then -- I'll make a PR soon
