### ISSUE TITLE
strange behavior opening a ```:term```: open 2 new tabs

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#2055]
There is a strange behavior when using the ```:term``` command: it looks like 2 new tabs get created, 1 is the terminal, 1 is an (additional) view of the window from which the terminal-opening command was issued. See screenshot (there are 2 tabs in the bottom half: 'welcome' and the terminal. Both were opened by the ```:term``` command while I would want only the terminal, it is strange to need to close 2 tabs when done :) ) :

![Screenshot from 2020-07-02 21-49-47](https://user-images.githubusercontent.com/8382834/86403417-f7bdda00-bcad-11ea-9ddd-195ce12e33d7.png)

**Comment by lessp** [comment]
Also experiencing this, also, not sure if related, but when tabbing between windows, `Welcome` is still there while not visible anywhere on screen and tabbing to it creates a new tab with it.

![image](https://user-images.githubusercontent.com/17602389/88193127-969a7e00-cc3d-11ea-8e1c-d1e34827e884.png)

**Comment by glennsl** [comment]
That's a different issue @lessp. See #1192. But this issue also applies to splits generally, not just terminals. The underlying problem is a bit of a chicken-and-egg one: You can't create a split without a buffer, and you can't create a buffer without it automatically opening a new editor since `libvim` currently isn't able to distinguish between buffers being open internally, buffers being opened externally and already opened buffers being switched to. They all just emit a `BufferEnter` event. So i think the proper fix here is to have `libvim` emit more fine-grained events.

**Comment by jerabaul29** [comment]
Would it be possible, as a temporary fix, that the ```:term``` command 1) split opening a new buffer as this is necessary, 2) opens the terminal in the new split 3) close the un-used buffer? Of course this is a relatively ugly patch, but would make things much more usable.

**Comment by bryphe** [comment]
Was looking at this along with #3150 - looks like this no longer reproduces
