### ISSUE TITLE
File explorer doesn't update on chages

### ISSUE THREAD

**Issue by kakamorsch** [onivim/oni2#2056]
Today I was trying the nightly version 2.0.3.0 and had the following "problem" the file explorer didn't update when I make changes on the working directory, if you create a new file or remove an existing one, the file explorer on the left won't update.

My operating system is the Windows 10 1909.

**Comment by Grinshpon** [comment]
I noticed this on Windows as well, but a quick workaround for now is to type `:cd .` which does update the explorer. I haven't looked through the repo too thoroughly yet, but I feel like since some commands update it and some don't, then it should be a matter of calling whatever function updates the explorer.

**Comment by CrossR** [comment]
We don't have a file watcher hooked up at the mo, so the commands that directly cause a change of directory, like `:cd` will `chdir` into that folder and cause a refresh. The rest of the commands like `:w` a new file, don't cause a refresh.

Ideally, we would set up a watcher, such that when an event happens in the current folder we can update the explorer and anything else that needs doing.

**Comment by MAHDTech** [comment]
I've also noticed this, and (at least on macOS) another workaround is that if you minimize and then expand the folder in the explorer UI, the new files will then appear.

cheers for the `:cd .` workaround, much easier 😄
