### ISSUE TITLE
Question/Feature request: Ability to remove trailing whitespace on save

### ISSUE THREAD

**Issue by drew887** [onivim/oni2#2100]
Hello! Not sure if this is the right place to be submitting a question like this and If I am missing an obvious option I am sorry :sweat_smile:  but is there currently a way to remove trailing whitespace on save? 

From what I can tell this is normally accomplished in vim with a line in your vimrc like 
```viml
autocmd BufWritePre * %s/\s\+$//e
```

however from what I understand vimrc support is not currently here and theoretically I was kinda expecting this to be present like the vscode option in the preferences file but it appears there is no option there.

**Comment by CrossR** [comment]
Native support, either in Oni2 or via a VSCode extension should be supported, though I think right now we are missing a "Format on Save" option, but it should come as we fix that for the rest of the formatters.

The native vim way should work as well, and testing it interactively (i.e. just typing the command you gave into the Oni2 command line) does work, so it should also work if you add it to the `experimental.viml` option of your config, though from a quick test, it looks like you'd need to mess with the escaping of the slashes in that string since it doesn't seem happy for me after a quick try.

**Comment by drew887** [comment]
Oh awesome! I missed that there was an `experimental.viml` option. Excited to hear that a native option could be coming but this works in the meantime. Thank you very much! :smile: :tada:
