### ISSUE TITLE
Clangd extension always shows autocompletion menu

### ISSUE THREAD

**Issue by ahellqui** [onivim/oni2#2139]
When using the clangd extension for c and c++ autocompletion suggestions show up even when the user haven't typed anything, this makes it impossible to use tabs for indenting.

## Expected behavior
Pressing tab should only trigger autocompletion if the user types something (footage from vscode with clangd extension):

![bug_report_vscode](https://user-images.githubusercontent.com/50931258/87860819-d06b3c00-c940-11ea-9788-537f0fd01b92.gif)

## Actual behavior
Pressing tab always triggers autocompletion menu:

![bug_report_oni](https://user-images.githubusercontent.com/50931258/87860846-07d9e880-c941-11ea-82c8-79ab832b4733.gif)

## Debug output gotten with -f --debug
[oni-debug.log](https://github.com/onivim/oni2/files/4942435/oni-debug.log)

## Steps to reprocuce
1. Install the clangd extension https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd
2. Create a .c file
3. Open it with Oni2
4. Enter insert mode
5. Press tab

## System information
- OS: Arch Linux
- Oni2 version: commit 1b9250b2

**Comment by ahellqui** [comment]
I just found issue #1133 that seems to show the same problem. I just thought I'd link it in case it can help you find a common denominator between the logs or something since it's different extensions.

**Comment by bryphe** [comment]
Thanks @ahellqui for the great bug report / details (gifs were very helpful) and for finding the dup!

This should be fixed now with the completion improvements brought in by https://github.com/onivim/oni2/pull/2202 (both the pop-up-sticking-around-after-completion and the duplicate `int`s showing in the completion menu).

The `clangd` extension is really nice - I'm looking forward to using it next milestone in working on libvim!

LMK if you're still seeing any undesirable behavior in the latest build. Will close for now as fixed by #2202 , but please feel free to reopen if there are still problems.
