### ISSUE TITLE
Pressing <C-p> while in command-line opens QuickOpen

### ISSUE THREAD

**Issue by romgrk** [onivim/oni2#216]
![Screenshot from 2019-04-03 13-49-52](https://user-images.githubusercontent.com/1423607/55500957-6e85a680-5617-11e9-8fec-db9f210069e3.png)

**Comment by bryphe** [comment]
Thanks @romgrk for logging the issue! I could see two possibilities for fixing this:

- __Option 1:__ Don't allow `<C-p>` / `<C-S-p>` actions while the command line is open
- __Option 2:__ Close the command line when a menu is open

I think Option 1 is probably the expectation - especially since `<C-p>` would have some behavior if there is a wildmenu open.

@Akin909 - is this something we need to fix by setting an input control mode for `<C-p>`/`<C-S-p>`?

**Comment by romgrk** [comment]
**Option 3**: bind QuickOpen to a command and map `<c-p>` to it in normal/insert/visual modes.

**Comment by Akin909** [comment]
@bryphe the fix here would be to set the input control to `MenuFocus` when either the commandline or wildmenu open, since they idea with that is it should tell other bits of UI where the current focus is but the wildmenu etc. pre-date that.

So the quick open is unaware that there is already another menu open, when it opens
