### ISSUE TITLE
Building on MacOS: "Unknown command: esy"

### ISSUE THREAD

**Issue by JasonMFry** [onivim/oni2#2192]
* OS: macOS 10.15.6
* favorite food: kimchi

I was following the instructions here https://onivim.github.io/docs/for-developers/building#macos. I did 

1. `brew install libtool gettext`.  I got this output (note that `libtool` is renamed to `glibtool`)
    ```sh
    Warning: gettext 0.20.2_1 is already installed and up-to-date
    To reinstall 0.20.2_1, run `brew reinstall gettext`
    ==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6_2.c
    ==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/af317b35d0a
    ##################################################################################################### 100.0%
    ==> Pouring libtool-2.4.6_2.catalina.bottle.tar.gz
    ==> Caveats
    In order to prevent conflicts with Apple's own libtool we have prepended a "g"
    so, you have instead: glibtool and glibtoolize.
    ```

1. `git clone https://github.com/onivim/oni2`
1. `cd oni2`
1. `esy install`. I got this output `fish: Unknown command: esy`. I tried in `bash` and `sh` just in case but always the same output: `SHELL_NAME: Unknown command: esy`

Is this an issue with `libtool` being renamed to `glibtool`? That's the only anomaly I can see in this otherwise straightforward process.

To preempt silly questions, yes I'm in the correct directory (`pwd`: `/Users/j/Projects/oni2`). Yes I really like kimchi. No it probably isn't my *favorite* food but gosh it's close.

**Comment by CrossR** [comment]
Hey! 

`esy` is a general build tool for ReasonML, and its a separate install. The docs are maybe a bit confusing since there is two sections, the general section and the OS specific bits. Also doesn't help when its a language you probably aren't familiar with so the distinction between "Oni2 specific stuff" and "general language-y things" is hard to know.

https://onivim.github.io/docs/for-developers/building#prerequisites lists what is needed for all platforms, and includes a link on getting `esy` setup, as well as a link through to revery since that has a dep or two of its own.

Hopefully with that and the few revery bits installed, the commands should then be happy.

**Comment by JasonMFry** [comment]
🤦 Reading is tough
