### ISSUE TITLE
Feature request: Add a warning message when opening an unsupported file type

### ISSUE THREAD

**Issue by MAHDTech** [onivim/oni2#2197]
If you accidentally select an unsupported file type from the File Explorer, such as a binary or PNG file, the editor will become unresponsive and not recover.

Would it be possible to filter based on the file type, and if an unsupported file is selected take a similar method to VSCode and prompt the user?

Currently, VSCode if attempting to open an unsupported file will display the following message.

> The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?

**Comment by CrossR** [comment]
I believe (well in my tiny 3 file test) that #2187 should have fixed the hang. I know see a bunch of rubbish but opening an image and even when opening the 80MB installer for Oni2 on Windows, after a quick pause it loads in fine.

However, it would be nice to have something like that. I believe (from a quick poke in the VSCode source) that they show that warning for both binary/unsupported files (I couldn't easily find there check for that yet) and for giant files. If we can find what they are doing to determine that, it would make sense.

A file type filter sounds like it would be too much work on our end potentially, so if we could get away with not having to maintain an ever growing list of "don't open these", that would be nice. (I'm just worried that I know like a jpg alone has jpg, JPEG and then the other weirder ones I've seen twitter use like jfif, jfi, jif, so that list would either be giant and a pain, or just annoying since it would have too many gaps to be useful.)

**Comment by MAHDTech** [comment]
Hi!

I've just downloaded the latest nightly,

> Version: 2.0.3.0
> Date: 29/07/2020, 14:23:00
> Commit: fc8ccb04

I can see from the change log that this includes PR #2187 as you mentioned.

And 🥁 , it works without crashing!

I don't receive a message, but the file is opened without crashing, jibberish and all 😁
