### ISSUE TITLE
What counts as commercial use?

### ISSUE THREAD

**Issue by trusktr** [onivim/oni2#2211]
What counts as commercial use vs non-commercial use? This would make it easier to understand the license.

**Comment by bryphe** [comment]
Hi @trusktr ,

Here's the relevant part of the EULA, if it helps:

> Under a Non-Commercial License, Licensee will not use the Software: (a) for any commercial, professional, for-profit and/or on-sale purpose or otherwise to provide any commercial service(s) to a third-party. (b) in the course of any employment or business undertaking of Licensee; (c) on any commercial premises during business hours (except where use of the Software is solely for a personal, recreational, educational, or other non-commercial purpose); and/or (d) to create any commercial tools or plugins.

Is there a scenario you're thinking about that isn't covered by that? Or maybe some gray area? The simplest way to think about is - if you use Onivim to make money (for an employer, selling software), it's commercial use. 

LMK if you have further questions - happy to help clarify! Can add an FAQ entry or something too if it would help.

**Comment by p00f** [comment]
Related question : oni2 is currently in the AUR (https://aur.archlinux.org/packages/onivim2/) as a source package (the user has to build it locally)
1) Am I allowed to build this and distribute on the AUR as a binary?(ie as onivim2-bin)
2) Can someone who binaries everything in the AUR and distributes binaries via custom pacman repositories (https://lonewolf.pedrohlc.com/) do this for oni2?
3) Do you think either of the above will hurt your sales?

**Comment by bryphe** [comment]
I'll close this out since there is more discussion in #2899

**Comment by bryphe** [comment]
Hi @p00f, 

Sorry I missed your question before! Thanks for checking in, appreciate your thinking about this.

I think the answer will be a bit simpler when we have public trial builds available (in which case - will be straightforward to distribute those). The main thoughts I have are:

1) With distributing built binaries, if they don't come from our build - there's a chance some dependencies could be broken (ie, the extension host not integrated correctly), or that it could've been modified between source <-> build. Worst case for me is that I get bug reports due to an incorrectly packaged dependency - they can often be time-consuming to debug.

2) Since we don't have the public-trial-builds yet, I'm trying to keep the feedback scoped as much as possible - avoiding having public builds so I can stay focused on the issues for users who've invested in the project. Then, once we're ready - broaden out the builds and get more feedback

I'll certainly encourage sharing the trial builds once we get to that point :sunglasses: 

In the meantime, the trade-off @marblenix set up with `brew` seems like a good compromise to me - it pulls the official builds, just requiring the user to set the license key via env variable: https://github.com/onivim/oni2/issues/1008

**Comment by p00f** [comment]
Understood, thanks!

**Comment by p00f** [comment]
1) has definitely happened to me heh
