### ISSUE TITLE
FontFallback endless loop (again?)

### ISSUE THREAD

**Issue by TheSamsa** [onivim/oni2#2286]
This might be related to #2269 BUT I tried it with a build from source too with the fix already there.
Also I have a different setup, first I use Manjaro linux (5.7.9-1-MANJARO), and do have a fontFamiliy configured. Initially I tried it with my usual coding font "Hack Nerd Font" and I couldn't open the main.go.
I then tried it with the "xos4 Terminus" font, with some kind of success. The file opened, but it displayed gibberish.

tail of the log with "Hack Nerd Font"

> (many lines above this)
[DEBUG]    +0ms Oni2.Store.dispatch : After: (FileExplorer
   (ActiveFilePathChanged
      (Some "/home/cschmidler/projects/insys/iotcore/barracuda/main.go")))
[DEBUG]    +0ms Oni2.Store.dispatch : After: BufferEnter {id = 3; fileType = (Some "go"); lineEndings = <opaque>;
  filePath =
  (Some "/home/cschmidler/projects/insys/iotcore/barracuda/main.go");
  isModified = false; version = 0;
  font =
  { fontFamily = <opaque>; fontSize = 14.; spaceWidth = 8.4287109375;
    underscoreWidth = 8.4287109375; avgCharWidth = 8.4287109375;
    maxCharWidth = 27.9384765625; measuredHeight = 16.296875;
    descenderHeight = 3.3017578125; smoothing = <opaque>; features = <opaque>
    };
  buffer = <opaque>}
[DEBUG]    +0ms Oni2.Store.Vim : Buffer update: 3
[DEBUG]    +0ms Revery.FontCache : Resolving fallback for: 	"git.insys-tec.de/iotcore/barracuda/cmd" at byte offset 0
[DEBUG]    +3ms Revery.FontCache : Unresolved glyph: character : U+0009 font: Hack Nerd Font
[INFO]     +0ms Revery.FontCache : Loaded : xos4 Terminus
[DEBUG]    +0ms Revery.FontCache : Got fallback font - id: 16 name: xos4 Terminus (from source font - id: 4 Hack Nerd Font)
[DEBUG]    +0ms Revery.FontCache : Resolving fallback for: 	"git.insys-tec.de/iotcore/barracuda/cmd" at byte offset 0
[DEBUG]    +0ms Revery.FontCache : Got fallback font - id: 16 name: xos4 Terminus (from source font - id: 4 Hack Nerd Font)
[DEBUG]    +0ms Revery.FontCache : Resolving fallback for: 	"git.insys-tec.de/iotcore/barracuda/cmd" at byte offset 0
[DEBUG]    +0ms Revery.FontCache : Got fallback font - id: 16 name: xos4 Terminus (from source font - id: 4 Hack Nerd Font)
[DEBUG]    +0ms Revery.FontCache : Resolving fallback for: 	"git.insys-tec.de/iotcore/barracuda/cmd" at byte offset 0

the commit I built with
`$ git rev-list HEAD -1`
`b5f8eaf78abb6d94b0571c64704394e9e218a278`

My settings:
> {
  "editor.detectIndentation": true,
  "editor.fontFamily": "Hack Nerd Font",
  "editor.fontSize": 14,
  "editor.largeFileOptimizations": true,
  "editor.highlightActiveIndentGuide": true,
  "editor.indentSize": 4,
  "editor.insertSpaces": true,
  "editor.lineNumbers": "on",
  "editor.matchBrackets": true,
  "editor.minimap.enabled": true,
  "editor.minimap.maxColumn": 120,
  "editor.minimap.showSlider": true,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "none",
  "editor.rulers": [],
  "editor.tabSize": 4,
  "editor.zenMode.hideTabs": true,
  "editor.zenMode.singleFile": true,
  "files.exclude": ["_esy", "node_modules", ".git"],
  "workbench.activityBar.visible": true,
  "workbench.editor.showTabs": true,
  "workbench.iconTheme": "vs-seti",
  "workbench.sideBar.visible": true,
  "workbench.statusBar.visible": true,
  "workbench.tree.indent": 2,
  "vim.useSystemClipboard": ["yank"]
}

If you need something else, maybe the full logs I can provide them if needed.

**Comment by bryphe** [comment]
Thanks for the details and grabbing the logs, @TheSamsa ! Very helpful.

I'm not able to reproduce this _exactly_ - but based on the logs I think I am able to reproduce an issue of the same class. What's happening is our font-fallback code is trying to get a glyph for the tab character (`U+0009`) from `Hack`, and failing - and it asks for a fallback font, and it gets `Terminus` - it tries to get a glyph for the tab character again, and fails. 

Our current logic assumes that, if we get a fallback font, it's able to produce a glyph for that character - and because that's not the case, we're spinning in an infinite loop. So we need to update our logic to handle that case.

A  couple other improvements:
- I'm adding a 'circuit breaker' - detecting when we get in a loop, and breaking - so that the worst case is we get an invalid glyph, as opposed to a hang.
- For ASCII characters - like `U+0009` - I don't think it makes sense to fallback, so we can stop that case too.

**Comment by TheSamsa** [comment]
Thanks for the fast response, I am itching to use oni2 :grin: 
Your proposal sounds reasonable, what struck me a bit was that those fonts do not have glyphs for `U+0009` which is just a `TAB`. But then again, I am not very familiar how fonts are handled.
