### ISSUE TITLE
Zoom In not mapped to "Control +"

### ISSUE THREAD

**Issue by dlagg** [onivim/oni2#2293]
I know you can set your keybindings. But it's strange that "Zoom Out" function are mapped to <kbd>Control</kbd>+<kbd>-</kbd> but <kbd>Control</kbd>+<kbd>+</kbd> instead of doing "Zoom In" jump 2 lines.

**Comment by bryphe** [comment]
Ah, yes, this is wrong - the way the `Zoom In` binding is set up is not ideal - it's currently bound to `<C-=>` 
https://github.com/onivim/oni2/blob/4617ffdb56198137f79687f3abf784e8eeac4302/src/Store/KeyBindingsStoreConnector.re#L24

The root cause is an issue with our input handling - we get the raw character press (on a US Keyboard -  <kbd>Control</kbd>+<kbd>Equal</kbd> => `+`). We need to fix this though so that we can get the actual 'produced' character for bindings.

Just curious - what platform (Windows / OSX / Linux) and keyboard layout do you use, @dlagg ?

**Comment by dlagg** [comment]
> Ah, yes, this is wrong - the way the `Zoom In` binding is set up is not ideal - it's currently bound to `<C-=>` 
> https://github.com/onivim/oni2/blob/4617ffdb56198137f79687f3abf784e8eeac4302/src/Store/KeyBindingsStoreConnector.re#L24
> 
> The root cause is an issue with our input handling - we get the raw character press (on a US Keyboard -  <kbd>Control</kbd>+<kbd>Equal</kbd> => `+`). We need to fix this though so that we can get the actual 'produced' character for bindings.
> 
> Just curious - what platform (Windows / OSX / Linux) and keyboard layout do you use, @dlagg ?
> 
> 

Currently spanish layout.
5.7.12-arch1-1
