### ISSUE TITLE
In i3 (linux), opening Oni2 in split view and switching to tabbed mode makes Oni2 quit.

### ISSUE THREAD

**Issue by woeps** [onivim/oni2#2316]
Oni 2 quits unexpected when switching from split view (windows side by side) to tabbed mode (nearly full screen, but having window titles shown as tabs) by using the keys: `super` (windows key) + `w`.

### Oni 2
- Version: 0.5.1-nightly
- Date: 8/17/2020, 6:25:02 AM
- Commit: 749848d0

### i3
- i3: 4.18.1 (2020-04-23)
- linux distro: Manjaro

## Log
[oni2.log](https://github.com/onivim/oni2/files/5088804/oni2.log)

**Comment by bryphe** [comment]
Thanks for reporting the issue, @woeps ! 

This looks like a bug with our default key bindings - for Mac, we bind `Cmd+W` to close a window (which is expected behavior)... but this key-binding was also active for Windows and Linux, which isn't expected and might collide with functionality like this. Going to scope those bindings just for Mac

**Comment by woeps** [comment]
I thought this could be caused by conflicting key bindings. But if I start oni2 in "tabbed mode" and press `windows + w` again nothing happens. This made me think there could be something else.
