### ISSUE TITLE
Syntax highlighting for XML files appears to be broken

### ISSUE THREAD

**Issue by synaptiqlabs** [onivim/oni2#2332]
Buffers with only XML content for which the filetype has been set as XML have no syntax highlighting visible.

Version 0.5.1-nightly
Windows 10 Build 18362

**Comment by CrossR** [comment]
This is because we don't ship with XML syntax highlights built in (you can see the list in `extensions/`).

If you install an extension, either from finding a custom one, or installing the default VSCode one, it should work.

(Instructions [here](https://onivim.github.io/docs/configuration/extensions), if you wanted the default VSCode one, you'd want to copy `extensions/xml` from the VSCode git repo, and follow the manual install instructions).

**Comment by synaptiqlabs** [comment]
Ah, understood. I guess I'll wait until the completion of VimL integration and see what can be done in the vein of Vim's XML ft plugin.

**Comment by CrossR** [comment]
If you need XML highlights now, it should just be a case of

```
git clone https://github.com/microsoft/vscode.git
cp -r vscode/extensions/xml ~/.config/oni2/extensions/
```
