### ISSUE TITLE
Code completions from vscode-go extension not working properly

### ISSUE THREAD

**Issue by mcesar** [onivim/oni2#2359]
Using the recommended configuration, accordingly to https://github.com/onivim/oni2/blob/29516143efa36fe3ac4e089b9a97ad8ee98b9fe6/docs/docs/languages/go.md, the code completion presents a strange behavior:
![GravaÃ§Ã£o de Tela 2020-08-25 Ã s 11 20 58](https://user-images.githubusercontent.com/1762579/91188189-66744e00-e6c7-11ea-97ea-26d6c183ae7c.gif)
As seen in the video, when I type `os.g` the methods starting with `G` does not show up, neither when I type `os.G`; however other methods appear.

However, if I type `os.g` (or `os.G`) and press ctrl-space, the methods starting with `G` appear.

**Comment by bryphe** [comment]
Hi @mcesar ,

Thanks for logging the issue and recording the gif!

> As seen in the video, when I type os.g the methods starting with G does not show up, neither when I type os.G; however other methods **appear.**

This is an interesting observation; it might be that we're not re-querying as we need to...

I tested this out on a simple, small test file:
```
package main;

import (
	"fmt"
	"os"
)

os.

func main() {
		fmt.Printf("Hello, world\n")
}
```

![2020-08-25 15 04 45](https://user-images.githubusercontent.com/13532591/91232763-99790a80-e6e4-11ea-8c4b-122d7be94eec.gif)

I'm wondering if, for this small test file, you hit the issue here too?

It could be that there are more completion items in scope here on the initial `.` key press (when we first ask for completions), and the go language server is sending us an `isIncomplete` flag to query again - which we aren't handling yet.

In addition, is the file you are working with open source? If so - I could test it out and see if I can reproduce it there.

**Comment by mcesar** [comment]
Hi @bryphe, 
> I'm wondering if, for this small test file, you hit the issue here too?
> 
Yes, I hit the same issue with this small test file.
> In addition, is the file you are working with open source? If so - I could test it out and see if I can reproduce it there.
>
I have this issue working in this open source project: https://github.com/mcesar/copier, as seen in the video bellow:

![onivim2](https://user-images.githubusercontent.com/1762579/91237057-f8a04480-e70f-11ea-94a7-63f856487ecf.gif)

**Comment by mcesar** [comment]
I just did a clean install of Big Sur and hit the same issue.
