### ISSUE TITLE
I want to pre-order, but my country is not listed there

### ISSUE THREAD

**Issue by segmentationfaulter** [onivim/oni2#243]
I am from Pakistan and Paypal does not support payments from here, how can I pre-order?

**Comment by bryphe** [comment]
Hey @segmentationfaulter ! Really sorry about the PayPal issue - that's a major bummer that PayPal doesn't work there.

Are any of the other funding platforms usable from Pakistan?
- [OpenCollective](https://opencollective.com/oni)
- [Patreon](https://www.patreon.com/onivim)
- [BountySource](https://www.bountysource.com/teams/oni)

We also have a bitcoin address for the project if that'd work. Let me know if you have other suggestions. 

Thanks for your interest in the project!

**Comment by segmentationfaulter** [comment]
I want to make a one time payment but none of the methods work here from Pakistan.

- Main site asks payments through Paypal.
- OpenCollective didn't work for me back then, now I think OpenCollective campaign is no longer active.
- BountySource also asks payment through Paypal, again it does not work for me.
- Patreon works for me but I want to make a one time payment and it supports recurring payments only.

Will paying through Patreon once and later cancelling will work for me to get a lifetime license?

**Comment by bryphe** [comment]
Hey @segmentationfaulter ,

Apologies for the late reply - was out of office for a bit. Thank you for trying out __all__ of those options, sorry that it is not a smoother process to pain from Pakistan.

> Will paying through Patreon once and later cancelling will work for me to get a lifetime license?

This will work! I am going to take a snapshot on August 1st - anyone who has paid any amount will get the lifetime license. You could go ahead and cancel after that first payment has gone through. (Immediately after I take the snapshot - I will be raising the price. But I'll make sure you get in before that 👍 )

Thanks for supporting the project!

**Comment by Xananax** [comment]
Where I live, PayPal is not an option. There are several blacklisted countries in Paypal, I just discovered Pakistan.

We don't know why; Paypal has been silent on the matter, has consistently deleted requests for explanations, and ignored petitions with thousands of signature (not even a "no comment"). They also don't disclose which countries are blocked in any official manner, which I personally find very unethical. If I subscribe to a worldwide payment service, I expect it to work everywhere, or at least tell me where it doesn't. You can get an idea of which countries are blocked [here](https://smallbusiness.chron.com/country-doesnt-work-paypal-66099.html).

I want to stress that fact that _absolutely any_ other payment gateway works worldwide; PayPal is the only one that blocks certain countries (and for no stated reason to boot). In other words, implementing absolutely _anything else_, at all, would be a solution. A marginal increase, for sure, as this audience is in specific third-world countries, but a gain nonetheless.

Granted, the countries blocked don't have a lot of purchasing power, but collectively, we are a few million people. The addressable market isn't huge (a lot of those people wouldn't be interested in indie games), but not negligible either. We are also incredibly non-vocal due to years of shrugs from the online community and total silence from Paypal, so lack of complaints does not mean that there isn't an opportunity cost (though I will acknowledge that this probably falls in the "we're dozens!" region).

There is also the ethical aspect, specially in relation to open source being linked to transparency, empathy, and progressive ideals. On top of the - already pretty iffy - practice of blacklisting countries for no good reason, Paypal has a [history of supporting less than stellar individuals and groups](https://en.wikipedia.org/wiki/PayPal#Criticism) (though I will also acknowledge they're doing better lately).

For all those reasons, I advise ditching Paypal and using Stripe (or any other provider), or at least providing an alternative.

In the meantime, how can I contribute? I'm will pay a monthly Patreon if I do actually use the software on a fairly regular basis, but for now, I would like to simply buy it. Does the trick above still work?

**Comment by bryphe** [comment]
Hey @Xananax ! Thank you for the detailed response.

>  They also don't disclose which countries are blocked in any official manner, which I personally find very unethical. If I subscribe to a worldwide payment service, I expect it to work everywhere, or at least tell me where it doesn't.

Wow! I didn't realize this... that is a major bummer. Very frustrating!

> For all those reasons, I advise ditching Paypal and using Stripe (or any other provider), or at least providing an alternative.

Based on the feedback here - I'm planning  / working on a Stripe integration but it probably will take a bit of time to roll out (it can be tough to balance time between the portal / payment processing / and actual working on the editor itself 😄 ). I'd like to have it available prior to the next price increase though - in the next month or so.

Unfortunately in the meantime I don't have a great alternative - if you wanted to do a 'one-time' donation to Patreon, you could cancel after the month - just annoying to deal with that on your end I'll update here once I have some initial Stripe integration, though, so we can test.

Thank you again for the details! Apologies that I don't have a better solution in the meantime, but we'll get this worked out.

**Comment by Xananax** [comment]
Done! I'll be supporting on Patreon. Thanks!

**Comment by everdimension** [comment]
Please support other payment options than PayPal.
The current paypal form seems buggy.
I have both russian and an american credit cards and I wasn't able to pay with neither of them (the form shows some obscure errors like "cannot use this card at the moment" or something like that).

I'd be glad to back this project and try the new alpha, but can't do it because of paypal.

**Comment by bryphe** [comment]
I did some prototyping with Stripe today - I think we should have some integration in place by end of next week. Sorry about all the PayPal issues!

**Comment by bryphe** [comment]
Unfortunately there's a little bit more work to do here - so I'm postponing it one more week (to 9/5)

**Comment by bryphe** [comment]
We've just updated / deployed our site with a new Stripe payment flow - if anyone here was having trouble, please try ordering again here: https://v2.onivim.io

🤞 that it works better now!

**Comment by bryphe** [comment]
I validated in a few cases that users who weren't able to purchase via the previous flow were now able to with our Stripe flow - so I'll close this out.

Aside from Stripe, there were several other improvements in the deploy:
- An e-mail sent out with the license key + more specific instructions on feedback / where to get the download
- The 'pre-generation' of a key that we used for PayPal in order to populate the invoice is no longer necessary.

Of course, if anyone is having issues with the flow, please feel free to open a new issue 👍
