### ISSUE TITLE
Adding saving when losing focus

### ISSUE THREAD

**Issue by Cogitri** [onivim/oni2#2431]
Hello,

I recently started using onivim2 after using VSCode for a rather long time. VSCode can automatically saves files when they lose focus (e.g. when switching tabs or focusing another window, e.g. a terminal), which makes quick edits very seamless (I don't have to :w -> enter). It'd be wonderful if onivim2 had something similar.

**Comment by bryphe** [comment]
Hi @Cogitri ,

Thanks for the idea! Yes, I like the idea of having an auto save option - VSCode exposes this configuration setting:

![image](https://user-images.githubusercontent.com/13532591/92980784-43c69100-f44c-11ea-9c61-bf5ade9b8615.png)

https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save

Would make sense to support this too in Onivim 👍

**Comment by gsa9** [comment]
VSCode doesn't have modes and, therefore, cannot know when it could be appropriate to perform a save while editing a file (other than after a preset delay, or lost focus).
But Vim is different, and better, in this respect. Vim knows when I have finished an edit: when I exit insert mode.

Vim’s modal editing "paradigm" (as Drew Neil put it, and illustrated very neatly in one of his vimcasts [http://vimcasts.org/episodes/modal-editing-undo-redo-and-repeat/](url)) lends itself to a better way (or extra option) if/when implementing auto-save in Onivim 2: auto-save whenever you exit insert mode (and the file has changed).

So auto-saving "after an edit" (after exiting insert mode, having changed the file) would be something worth considering for Onivim 2, to make it more powerful than VSCode in this respect, since it has modal editing and thus knows more about my actions and intentions. I enter insert mode, edit something, exit insert mode: an "atomic" edit was just made, save it!

For example, consider my (convenient) workflow for editing a foo_main.tex file in Vim.

I use Latexmk [https://mg.readthedocs.io/latexmk.html](url) running separately with:

latexmk -pvc

see: [https://tex.stackexchange.com/questions/15342/automatically-start-the-necessary-pdflatex-runs-if-tex-has-changed-macos-x](url)

I installed this plugin in Vim:
[https://github.com/vim-scripts/vim-auto-save](url)

Whenever I change something in any of my TeX source files (in Vim) the changes are auto-saved (by the vim-auto-save plugin), and the preview (foo_main.pdf) is automagically updated.

For vim-auto-save, I added these lines to my .vimrc:
let g:auto_save = 1  " enable AutoSave on Vim startup
let g:auto_save_in_insert_mode = 0  " do not save while in insert mode

AutoSave will display on the status line on each auto-save by default:
(AutoSaved at 08:40:55)

You can silence the display with the g:auto_save_silent option:
let g:auto_save_silent = 1  " do not display the auto-save notification
