### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ek203** [onivim/oni2#2451]
Hi,

I had to install esy 0.6.2 because of incomptability they have with my OS version

```
 ~/oni2 (master)$ esy install
info install 0.6.2 (using package.json)
info checking https://github.com/ocaml/opam-repository for updates...
info checking https://github.com/esy-ocaml/esy-opam-override for updates...
info resolving esy packages: done
info solving esy constraints: done
error: No solution found:

Conflicting constraints:
  Oni2 -> ocaml@=4.11.1000
  Oni2 -> reason-native-crash-utils -> ocaml@>=4.7.0 <4.11.0


esy: exiting due to errors above
```
Any solution?

**Comment by CrossR** [comment]
Is this with a clean / unchanged version of the Oni2 repo? The current main branch is pinned to ocaml `4.7` I believe, with a PR for `4.10`, so it looks like those options are being ignored as its trying to use `4.11`.

**Comment by bryphe** [comment]
This looks like a bug w/ the solver that is fixed in later versions of `esy` - we require `esy@0.6.6` to build Onivim at the moment.

> I had to install esy 0.6.2 because of incomptability they have with my OS version

Would recommend logging an issue here in `esy`'s tracker, with the specific error in installing newer `esy` versions (along with the information about your platform) - sounds like a bug with `esy` that should be fixed: https://github.com/esy/esy/issues
