### ISSUE TITLE
rust-analyser not updating diagnostics

### ISSUE THREAD

**Issue by flukejones** [onivim/oni2#2490]
Per title. Have tried various settings for this including nightly. While it appears that LSP interactions for predictions etc work fine, I never get updates from the "rust-`analyzer.checkOnSave.command": "clippy",` setting which should run either `clippy` or `check` on save.

**Comment by flukejones** [comment]
A very quick way to check if this is working is with the following code snippet:

```
fn main() {
  let x:u8 = 42;
}
```
change `42` to `'x'` and save, you'll get an error highlight if clippy/check runs on save.

**Comment by bryphe** [comment]
Thanks for the helpful repro!

Looks like this was fixed by https://github.com/onivim/oni2/pull/2999 as well, which sends the appropriate notification to the extension host on save. 

Now, when I save, I get the diagnostics updating:
![2021-01-20 14 00 40](https://user-images.githubusercontent.com/13532591/105246399-0e336200-5b28-11eb-9259-a9a95dc1698b.gif)
