### ISSUE TITLE
Auto completion does not work on Pop OS 20.04

### ISSUE THREAD

**Issue by abrabant-42** [onivim/oni2#2562]
Hello, first of all I want to thank you for this really great project. I backed it yesterday and I am not disapointed, however I can't get the autocompletion to work which is annoying.
I read that autocompletion should be enabled by default, and should work out of the box. Then I don't really know what to do to make it work.

I tried `oni2 -f` and `oni2 -f --checkhealth` to see if something was not loaded correctly, but it seems that everything is fine.
The build I'm using is `Onivim 2 (0.5.0)` (output of `--version`).

I installed oni2 by downloading the tarball and running the AppRun executable. I tried with the last nightly build too, with the AppImage. No one worked.

I tried `CTRL-n` to make the autocompletion menu show up, even if it should happens automatically: this does not work either. 

Anyway I think this project will be awesome, that's why I'm backing it. Maybe I'm missing something, but I do not see what to do at this point.

**Comment by CrossR** [comment]
Hi!

What project/language is this on? We ship with built in support for Reason/OCaml and JS/TS I think, and then for any other language you'll need to install an extension (as well as any dependencies of that extension). We have some tested extensions written up in the user manual for a few languages : https://onivim.github.io/docs/languages/reason-ocaml.

If a language is missing from there, it doesn't mean it won't work, just that its not a language we've tested, though we welcome documentation contributions to extend the languages listed there. Usually, it should be a case of finding an extension in Oni2 (or possibly on the VSCode marketplace itself if its missing from Oni2), and installing that. That process is here: https://onivim.github.io/docs/configuration/extensions.

**Comment by abrabant-42** [comment]
It was for C, but thanks now it is fixed thanks to clangd. I was thinking that a kind of "basic" autocompletion should be available (like vim one) but nevermind, I did not read the manual accurately.

**Comment by CrossR** [comment]
Ah! We have a separate issue for hooking up the most basic "Please just suggest words that exist in this buffer/open buffers" since that should just be available for everything as you've said. https://github.com/onivim/oni2/pull/1227 is an experiment around that, or #1862.

Language specific stuff we can't really include, as it could end up being more confusing if we included the C++ ext, but you'd still need some stuff installed locally etc. In which case, you don't get to see/know about the extension or its documentation, so you wouldn't know necessarily to install anything. Reason/OCaml is a bit different as that is easy to include and Oni2 is written in that. Same for JS/TS, since we already have node for the VSCode extension host, that is "free".
