### ISSUE TITLE
Search: Add option for RegEx search

### ISSUE THREAD

**Issue by keforbes** [onivim/oni2#2599]
If I search for `log` I get 78 results.  If I search for `log(` I get 0 results.  This is because it's actually doing a regex search and not a simple text search.  The regex was invalid so the search didn't run at all.

If I try `log()` it finds 78 results again because while the regex was valid, the empty `()` has no effect so it really only searched for `log`.  If I escape the `\(` then it finally searches for the text string `log(`.
![regex_find](https://user-images.githubusercontent.com/817509/96512054-2f30a200-121d-11eb-978c-9ad788e44254.gif)

I find this behavior unintuitive.  When first entering this screen, I had no idea it was doing a regex search.  If there was a red error  message saying "invalid regex" when I searched for `log(` I would've understood it wasn't just a basic text search.  Instead, I spent way too much time wondering why I couldn't search for an open parenthesis `(`.

Ideally, it'd be best to have a checkbox below the text input field which allowed me to enable/disable Regex Search.  That way, I would know the search supports regex but I could also choose whether or not I want that behavior.

**Comment by CrossR** [comment]
Definitely, a VSCode style toggle would be great here:

![image](https://user-images.githubusercontent.com/10038688/96515675-a2f29f00-125d-11eb-9dd5-4b89f2286db4.png)

(Which is Case toggle, whole word toggle, and regex toggle respectively).

Slowly supporting the full VSCode like search UI would be really nice:

![image](https://user-images.githubusercontent.com/10038688/96515921-10063480-125e-11eb-8b65-caac9c1d7f7d.png)

The arrow opens up the replace menu, the three dots opens up the "include/exclude" menu. Especially nice in monorepos like this to ignore some other code for now, or ignore tests when you are looking for something.

Since its powered by ripgrep, I think adding support for those 3 buttons wouldn't be too hard, and would be very useful, for the exact reason given here, where its non-obvious right now its a regex search...since none of the rest of the searches (fuzzy finder etc) are.

If regex is supported, a red highlight or something or a pop up error message under the box for invalid regex would be nice.
