### ISSUE TITLE
Ctr+Tab menu is no longer ordered by most recently used

### ISSUE THREAD

**Issue by glennsl** [onivim/oni2#2605]
...and hence a quick tap of Ctrl+Tab no longer works to switch to the previous editor either.

This was implemented in #1025 and used to work, but the menu now seems to ordered by last opened.

Possibly caused either by `lastUsed` on each buffer not being updated properly, or the menu no longer being sorted by `lastUsed`. From a quick glance through the code I can't see definite evidence of either, but there has been a major refactor since #1025 with the `BufferEnter` action previously used to update it being replaced by several different mechanisms in `Feature_Buffers`.

**Comment by sklirg** [comment]
This happened to me too when I upgraded on the 10th of October (nightly build). I remember the behaviour changed from most recently used to the order of files opened (?), and I thought it might have been a changed default setting, but I haven't done any custom configuration. I searched for issues/PRs related to this on the 10th, but found nothing - so I've just been living with it since. Would love this to revert back to most recently used, or at least a configuration option for how this should work. 👍

**Comment by glennsl** [comment]
Can you recall when you last upgraded before the 10th, @sklirg? If so that would hopefully give us a relatively narrow time range to look for potential culprits in the source code. Unfortunately I have no clue myself, but I have experienced this for several weeks at least.

**Comment by sklirg** [comment]
> Can you recall when you last upgraded before the 10th, @sklirg? If so that would hopefully give us a relatively narrow time range to look for potential culprits in the source code. Unfortunately I have no clue myself, but I have experienced this for several weeks at least.

Sadly, no. I've been upgrading to latest nightly _pretty much_ every morning (EU time), so I've gotten the freshest builds every day for quite some time. It's a manual process (`brew upgrade` with a custom/personal cask), so it might have slipped for some days.

**Comment by glennsl** [comment]
No worries. Just knowing that it's on the order of days rather than weeks months is very helpful!

I don't update very often myself as I build it from scratch in a sandboxed environment, which renders my computer useless for half an hour or so every time. I'm very much looking forward to auto-update landing!
