### ISSUE TITLE
Unable to create skia context: Windows 10

### ISSUE THREAD

**Issue by iamim** [onivim/oni2#2632]
Fails to start, then goes to idle mode. Attached is the log file created with `--debug` flag.
OS: W10 Pro 2004, build 19041.572

Please let me know if you need more info. Will be glad to help :)

[oni2.log](https://github.com/onivim/oni2/files/5445544/oni2.log)

**Comment by bryphe** [comment]
Thanks for the logs, @iamim ! This looks similar to #1522 / #1809 / #1842 - in our nightly builds, we now use ANGLE (DirectX instead of OpenGL) - which tends to be supported.

The fix to use Direct3D / ANGLE (#2283) is in the nightly builds (0.5.1), but not in the 0.5.0 - would you mind trying the nightly to see if that fixes the issue?

**Comment by iamim** [comment]
Hi @bryphe , I will test it tomorrow.

**Comment by iamim** [comment]
The nightly build worked, thanks!
