### ISSUE TITLE
Some questions about the EULA

### ISSUE THREAD

**Issue by jaredly** [onivim/oni2#268]
So I'm super interested in this funding model, and I'm excited to see it succeed :) These are my initial reactions to reading through the EULA, also IANAL but I like to understand what I'm agreeing to 😬

> 1.4 (e) use the Software for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for services, product or software offered by Company;

This sounds like it means "You can't use Oni as a code editor to edit the code of a competing editor", which is Very Weird. Is that what it means?

> 2.1 (a) Under a Non-Commercial License, Licensee will not use the Software: (a) in conjunction with any other copies or versions of the Software, under any type of License model;

Does this mean that, should Oni implement a collaborative editing feature, users w/ a Non-Commercial license would be unable to collaboratively edit with users w/ a Commercial license?

> 3.1 (b) Licensee shall in respect of the Source Code comply strictly with all other restrictions applying to its use of the Software under this EULA **as well as any other restriction or instruction that is communicated to it by Outrun Labs at any time during the Agreement.**

This "that is communicated" bit seems unreasonably general. Could it say something like "any updates that are made to the EULA" to at least restrict it to instructions given in writing?

> 4.1 Outrun Labs owns and will retain all legal rights in the software

How does this relate to contributors from outside of Outrun labs? Seems like it would be something of a barrier to contribution.

> 6.5 If Licensee wishes to opt out of auto-renewal, then You must email license@outrunlabs.com providing details of the Subscription Licenses which you wish to opt-out

Hopefully this would be updated to some more automatic process in the future?

**Comment by bryphe** [comment]
Hey thanks for the feedback @jaredly ! I have a call with our lawyers on Thursday, so I may have to forward on a few of the questions then, but just wanted to let you know I read through and I'll get some answers.

Ideally, we could end up with a license that could be usable for other apps to go with a dual-license approach, so this feedback is helpful!

>  These are my initial reactions to reading through the EULA, also IANAL but I like to understand what I'm agreeing to 

Totally understandable! 👍 

> > 1.4 (e) use the Software for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for services, product or software offered by Company;

> This sounds like it means "You can't use Oni as a code editor to edit the code of a competing editor", which is Very Weird. Is that what it means?

Hmm, ya, good catch - reading through that it does seem unnecessarily restrictive. I'll check on this clause and see why it was necessary in the context (or if its possible to eliminate).

>  > 2.1 (a) Under a Non-Commercial License, Licensee will not use the Software: (a) in conjunction with any other copies or versions of the Software, under any type of License model;

> Does this mean that, should Oni implement a collaborative editing feature, users w/ a Non-Commercial license would be unable to collaboratively edit with users w/ a Commercial license?

Good question - I'll check this too. This is a scenario we would like to support, there would be no need to restrict that 👍 

> This "that is communicated" bit seems unreasonably general. Could it say something like "any updates that are made to the EULA" to at least restrict it to instructions given in writing?

I believe there was a specific reason for this verbiage in the context of our licensing model; in that some instructions may need to be external to the EULA (like the billing plan represented on the invoice). Will double-check though and see if there is a way to streamline or clarify this.

> > 4.1 Outrun Labs owns and will retain all legal rights in the software

> How does this relate to contributors from outside of Outrun labs? Seems like it would be something of a barrier to contribution.

I remember discussing this; this clause is actually important because we need to retain IP rights to the software to be able to sell it (and is also important for the 'software-is-licensed-not-sold' aspect). 

The important aspect for contributors is actually the CLA: https://gist.github.com/bryphe/bf98297731dd69b9b580ca1d7fd2b90e (which gives us the ability to relicense and distribute the contributions).

Our 'hedge' against this is to dual-license all commits - 18 months after a commit is in master, we'll 'dual-license' it under MIT - so that commits that end up in the project eventually end up in the open.

One other aspect I was thinking about with this, but didn't get to finalize with our legal team, was to see if we could dual-license external contributions _immediately_.

> > 6.5 If Licensee wishes to opt out of auto-renewal, then You must email license@outrunlabs.com providing details of the Subscription Licenses which you wish to opt-out

> Hopefully this would be updated to some more automatic process in the future?

Oh, ya - this clause doesn't mean this is the only way to opt-out (you don't have to enumerate all possible ways here) - we just needed a sure-fire fallback that would always be available to include in the EULA. Once we roll out a monthly pricing plan, we'll also roll out a portal that makes it easy to unsubscribe from the web (or have a subscribe / unsubscribe ability directly from in the editor). 

Just wanted to share a couple thoughts so you know its on our radar - IANAL - but I'll follow up w/ more details after I've had a chance to run these by our legal team.

**Comment by jaredly** [comment]
Cool, thanks for the prompt response :)

> One other aspect I was thinking about with this, but didn't get to finalize with our legal team, was to see if we could dual-license external contributions immediately.

That would be awesome!

**Comment by bryphe** [comment]
Just wanted to follow up - I got off the phone with our lawyer and they were amenable to these changes:
- Removing the non-compete clause in 1.4e
- Removing the cross-license restriction in 2.1a
- For 3.1b, they said its ideal to have something in place, but we could tweak it and offer a timeline for updates (I was incorrect when I was communicating the reason for it). Waiting on updated verbiage
- For 4.1a - that clause needs to remain, however, we can allow external contributors to dual-license via MIT immediately. Just need to update the CLA to reflect this.
- For 6.5 - We can tweak the copy to reflect that it isn't the _only_ way to opt-out

Once I get the set of edits, I'll post up a revised EULA / CLA.

Thank you for reading through and the feedback, @jaredly !

**Comment by CrossR** [comment]
The revised EULA/CLA are public now as far as I can see!

Should we close this out?
