### ISSUE TITLE
No display in terminal window when launched from finder when not added to os path (macOS)

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#2686]
There seems to be a regression with the terminal display (downloaded today's nightly for macOS) where there is no display in the terminal window when launched from finder.  However after adding oni2 to the os path and launching from the terminal it works fine. Then when launching from finder/spotlight after that the terminal displays correctly.  I can't post a screenshot anymore as it now works fine for me, but will be an issue for new users (I just setup a new machine) that haven't yet added oni2. to the system path.

**Comment by bryphe** [comment]
Thanks for reporting the issue, @yunti !

Trying to reproduce this - what version of OSX does the machine have? I'm assuming Catalina / 10.15? 

I haven't been able to reproduce it yet - but it's interesting that the problem went away after the first time launching from the terminal. Trying to set up a fresh catalina install to reproduce that issue.

I noticed that, on catalina, we're defaulting to the `bash` shell instead of `zsh` for some instances - but I don't think that would cause the terminal not to show at all.

**Comment by bryphe** [comment]
I haven't been able to reproduce this in the latest builds (I've been exercising this as a test case: https://github.com/onivim/oni2/blob/master/manual_test/cases.md#12-validate-launches-from-dock-in-osx-2659)

Let me know if you happen to see it again, though
