### ISSUE TITLE
[Windows] command to enter terminal normal mode differs from instructions

### ISSUE THREAD

**Issue by dusty-phillips** [onivim/oni2#2778]
The documentation says that the command to enter terminal mode is `ctrl+\`, `ctrl+N`, but it wasn't working for me on Windows 10. I saw some PRs that change the docs and a fix for the command on MacOS, but after trial and much error, I determined that the command to get into terminal mode on Windows is actually `ctrl+\` `N`.

Not sure if the documentation needs to have a "on windows command is `ctrl+\, N` or if the program needs to be modified to match what it sounds like the macos behaviour is.

**Comment by bryphe** [comment]
Hi @dusty-phillips ,

Thanks for logging the issue!

Just curious - which build were you using (the `nightly` or `stable`)? There was a fix to make `ctrl`+`\`, `ctrl`+`N` work, but it came in after the latest `stable` build (PR #2413). If you're not sure - you can use the `:version` command to check.

Wondering if this is the same issue fixed in #2413, or if there is another issue past it
