### ISSUE TITLE
VS Code Extension Version Outdated

### ISSUE THREAD

**Issue by dcalhoun** [onivim/oni2#2779]
I'm unsure if I am merely misunderstanding the current status of VS Code extension support or if this is an untracked bug. Please feel free to close this issue if it is unneeded. 

When installing a VS Code extension, the version available for install is often an old version of the given plugin. For example, [`rescript-vscode`](https://marketplace.visualstudio.com/items?itemName=chenglou92.rescript-vscode) is currently published as `1.0.0`, but Onivim2 only displays a `0.0.3`. Uninstalling and reinstalling the extension does not result in the latest version of the extension being installed.

Semi-related, I am unable to determine how one should upgrade a VS Code extension that is already installed. Does this functionality exist?

<img width="1904" alt="onivim2-outdated-vs-code-extension" src="https://user-images.githubusercontent.com/438664/100567120-6323cc00-328d-11eb-9620-5922e5b3f0ef.png">

## Steps to Reproduce

1. Click the Extensions tab in the toolbar.
1. Search for "rescript".

## Expected Result

`rescript-vscode@1.0.0` is listed.

## Actual Result

`rescript-vscode@0.0.3` is listed.

## Environment

Onivim2: 0.5.1-nightly (0.5.1695)
OS: macOS 10.15.7

**Comment by CrossR** [comment]
We actually don't use the VSCode marketplace (its license means that only VSCode can use it), so we, along with other VSCode compatible editors like VSCodium use https://open-vsx.org.

It is most likely that rescript-vscode hasn't been published to open-vsx with the new version, so its out of date there. We can either update and push it ourselves, or ideally they can start publishing to Open-VSX directly.

For now though, since you can download the file from their GitHub (https://github.com/rescript-lang/rescript-vscode/releases/tag/1.0.0) you can do that, and install it manually with the CLI: https://onivim.github.io/docs/configuration/extensions#install-via-the-cli. (The VSCode marketplace isn't supposed to be used to download those VSIX files manually I believe either, so going direct to the source is best).

As for updating, I believe there is some functionality there for it, though not the most feature complete yet.

**Comment by dcalhoun** [comment]
@CrossR ah, OK! Thank you for the explanation. I overlooked those details in the documentation. I will close this issue.
