### ISSUE TITLE
Unable to create mappings with colon.

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni2#2883]
I opened the command prompt to create mappings and it would not accept mappings that involved `:`.
(I map `;` to `:` in normal mode to save myself the shift key).
I think there may be issues with other kinds of mappings, but I can't recall which exact ones failed. I'll reply here with more info if I come across those again.

**Comment by bryphe** [comment]
Thanks for logging the issue, @jordwalke !

There's a gap in our input handling code right now - it's only handling direct key productions (so our input code sees `:` as `shift+;`, which isn't great... since it doesn't handle multiple keyboard layouts). When we try to bind `:`, we get a failure since the current code can't find a `:` keycode on the keyboard.

Various keys that require shift pressed that would be expected to bind correctly like `+`, `?`, `_` are also impacted by this (and AltGr keys...).

@zbaylin set up the framework in https://github.com/onivim/oni2/pull/2687 for us to handle this correctly - I need to get it hooked up. 

Also related to https://github.com/onivim/oni2/issues/2114

**Comment by bryphe** [comment]
Some regressions have been identified with #2902, so I'll back it out and work through bringing it back in

**Comment by bryphe** [comment]
Actually - tracking those issues separately in #2916 - fix still in :smile:

**Comment by jordwalke** [comment]
Looks like the latest release fixes this. Also fixed my other mapping `inoremap <C-a> <c-o>^`!
Update process was so smooth, thank you!

**Comment by bryphe** [comment]
Awesome - thanks @jordwalke for confirming! (and thanks @zbaylin for all the work setting up auto-update 😄 )
