### ISSUE TITLE
What constitutes commercial use?

### ISSUE THREAD

**Issue by trusktr** [onivim/oni2#2899]
I'm curious about the license. What constitutes commercial use.

If we use the editor while writing a commercial product, is that commercial use?

Or do would it be something like modifying the editor (or not) and selling it?

**Comment by marcinkoziej** [comment]
I am  not an Oni2 developer.

There is an explanation of Non-Commercial in context of established Creative Commons licenses here: https://wiki.creativecommons.org/wiki/NonCommercial_interpretation

It might nor might not apply to intentions of Oni2 copyright holders; but might explain something for You!

**Comment by CrossR** [comment]
I think this section of the EULA covers this:

> Under a Non-Commercial License, Licensee will not use the Software: (a) for any commercial, professional, for-profit and/or on-sale purpose or otherwise to provide any commercial service(s) to a third-party. (b) in the course of any employment or business undertaking of Licensee; (c) on any commercial premises during business hours (except where use of the Software is solely for a personal, recreational, educational, or other non-commercial purpose); and/or (d) to create any commercial tools or plugins.

Broadly, if you are being paid for it, or using it to write something to make money, then that probably constitutes as commercial usage. There is some caveats around that, but its a good start (though read the EULA if you are interested further, since that is the actual license, not my vague interpretation!).

There is also the oni2-mit repo, which is fully open source and MIT licensed.

**Comment by bryphe** [comment]
Potential dup of #2211 

> If we use the editor while writing a commercial product, is that commercial use?

Yes, this would be considered commercial use - a good litmus test is if you are using to earn money (wage/selling something) - that's commmercial use.

> Or do would it be something like modifying the editor (or not) and selling it?

Redistributing isn't allowed by the EULA (for the Oni2 repo): 

```
1.4 Restrictions on Use.

You shall use the Software strictly in accordance with the terms of this Agreement and shall not: (a) distribute the Software (b) make the Software available over a network or other environment permitting access or use by multiple users at the same time; (c) violate any applicable laws, rules, or regulations in connection with Your access or use of the Software;
```

We may amend that though when we have the trial builds available (to allow distribution of non-modified builds).

However, in any case, this is why we have the time-delay licensed repo: [`oni2-mit`](https://github.com/onivim/oni2-mit)  - those commits are relicensed under MIT after 18 months so you're free to modify, use non-commercally, redistribute, etc - no limits. And by design - everything eventually ends up there. We have a script that runs nightly that takes the 18-month-ago commit and relicenses it.

Let me know if you have any other questions. Happy to add to the FAQ too

**Comment by p00f** [comment]
Is packaging binaries from unmodified source considered "redistribution"
