### ISSUE TITLE
Extension: Ionide-fsharp extension does not work

### ISSUE THREAD

**Issue by Karfroth** [onivim/oni2#2974]
Hi. I tried to use Ionide-fsharp extension with onivim2 but it seems to me it completely does not work at all.

**Environment**

Ubuntu 20.04
dotnet sdk 5.0.101
Onivim 2 Nightly 19d5f95f

**Step to reproduce**

1. Install C# extension with `oni2 --install-extension muhammad-sammy.csharp` command
2. download `Ionide-fsharp-5.1.0.vsix` from https://github.com/ionide/ionide-vscode-fsharp/releases/tag/5.1.0
3. install ionide plugin with `oni2 --install-extension Ionide-fsharp-5.1.0.vsix` from download directory
4. Open a F# project and open any fs file(I tried `dotnet new console -lang=F# -n=${project name}`.)

**Expected Behavior**

- Auto completion
- Warning
- Function/variable/module information with hover
- Whatever works on VSCode

**Observed**

- Nothing works
- From the log, I can find several erros
    - Unable to parse OutputService method: $append
    - Unable to parse OutputService method: $reveal
    - Unhandled method: $registerDebugAdapterDescriptorFactory
    - Unhandled method: $registerDebugConfigurationProvider

**ETC**
I tried 0.5.2 but it does not work neither.

**Comment by bryphe** [comment]
Hi @Karfroth ,

It looks like the issue is the `extensionDependencies` defined in the `package.json`:
https://github.com/ionide/ionide-vscode-fsharp/blob/ab871e5bcfec001bbc81ef5b331fbc0bb732b1b8/release/package.json#L1568

If I modify that `package.json` manually - it seems to work for me now. The `0.5.1` version showed an error on startup, but that went away with `0.5.2` - so I'd recommend that one:

Looks like, after making that change, I get basic hover/goto-definition/completion as expected:

![2021-01-14 16 37 31](https://user-images.githubusercontent.com/13532591/104665774-13effa00-5687-11eb-84f0-054bc8129c6f.gif)

The ideal fix would be to have the ionide project publish a version on Open-VSX, with the correct `extensionDependencies`. This comes up with a few different extensions, though, so I've considering patching Onivim to remap the `"ms-dotnettools.csharp"` reference to `muhammad-sammy.csharp`. It'd also be cool if VSCode supported optional dependencies: https://github.com/microsoft/vscode/issues/6384
