### ISSUE TITLE
clangd has random includes for auto complete

### ISSUE THREAD

**Issue by DLMartin-** [onivim/oni2#3022]
Hello, 
First I want to say that onivim2 is great, and exactly what I've been looking for! I was always annoyed that I couldn't navigate everywhere using vim in clion or vscode, so I'm very excited about onivim2! 

I am using onivim2 0.5.9, running on manjaro. 

I followed the instructions to enable the clangd language server, and generated a compile_commands.json using cmake. 
However, I am getting random includes that I don't care about, and none of the includes I do care about (like vector or array). However, including them does not cause any errors as far as compiling or building goes. They just don't show up in the popup! 
![vector](https://user-images.githubusercontent.com/2279024/105288295-d5c27100-5b85-11eb-99ec-1228e3b291d4.png)

I checked to see where clang++ was pulling in includes, and it is looking in my /usr/include/c++/v1. This is also backed up by clangd being able to "see" the algorithm header (for some reason?), and doing a gd over that include takes me to /usr/include/c++/v1/algorithm.
![algorithm](https://user-images.githubusercontent.com/2279024/105288286-d529da80-5b85-11eb-8fbb-5c71f4e8dd30.png)

Below is my compile_commands.json -- as far as I can tell, everything looks correct. I've tried passing in -I/usr/include/c++/v1 as well, but to no avail.

```
[
{
  "directory": "/home/acorn/Documents/test/build",
  "command": "/usr/bin/clang++    -o CMakeFiles/testmain.dir/src/main.cpp.o -c /home/acorn/Documents/test/src/main.cpp",
  "file": "/home/acorn/Documents/test/src/main.cpp"
}
]

```
It almost feels like the popup menu is overloaded and so its just picking and choosing random files & folders to display? Is that the case, and is there a way to better configure it?

Other than this annoyance, I'm loving onivim2 so far.

**Comment by bryphe** [comment]
Hi @DLMartin- ,

> First I want to say that onivim2 is great, and exactly what I've been looking for! I was always annoyed that I couldn't navigate everywhere using vim in clion or vscode, so I'm very excited about onivim2!

This is awesome to hear, thanks for the kind words :smile: 

> It almost feels like the popup menu is overloaded and so its just picking and choosing random files & folders to display? Is that the case, and is there a way to better configure it?

Thanks for sharing the screenshots + the `compile_commands.json` - I was able to reproduce this on Manjaro box. 

The root cause is a bug with our completion implementation - we're not handling the `isIncomplete` flag from the extension host. This is letting us know we should continue to re-query as the user types, but right now we aren't handling that correctly.

> It almost feels like the popup menu is overloaded and so its just picking and choosing random files & folders to display? Is that the case, and is there a way to better configure it?

This is pretty much spot-on - since we don't have that `isIncomplete` flag to re-query, `clangd`'s header completion is limited by the `--limit-results` argument, which [defaults to `100`](https://manpages.debian.org/experimental/clangd/clangd.1.en.html). So we're essentially the first 100 headers it seems are important, and missing some others.

The ultimate fix is for us to properly handle the `isIncomplete` flag in Onivim and re-query - in the meantime, a workaround is to set the following configuration to override the `--limit-results` setting:
```
  "clangd.arguments": ["--limit-results=0"]
```
(the only concern would be perf - if there are cases where it tries to return a _lot_ of headers - `0` means no limit, so could simply try a larger limit like `500`).

With that configuration change, I now get the `vector` header:
![image](https://user-images.githubusercontent.com/13532591/105408434-cf62e200-5be3-11eb-9497-bf243f042128.png)

Related to a few other cases where completion has issues due to not handling the `isIncomplete` flag: #1948 #2359

**Comment by DLMartin-** [comment]
This worked great, thank you! I'll keep this in mind, and now I have a reason to learn... uhh Reason...

Is there documentation of all the different configuration settings somewhere? I saw what was listed out on [Onivim2 Settings Configuration in the User Manual](https://onivim.github.io/docs/configuration/settings), but I can't seem to find anything on the "clangd.arguments" in the extensions repo, and searching for "clangd.arguments" yields a bunch of results just talking about setting up a compile_commands.json file.

Thank you so much again for the help!
