### ISSUE TITLE
vim commands ( :command ) dosn't take any affect

### ISSUE THREAD

**Issue by DvirSadeh** [onivim/oni2#3049]
Inserting vim commands (like `:cd`, `:e`, `:term`) do nothing. The little upper window appears when I insert `:`, and the autocomplete works, but after I press Enter nothing seems to happen.

- macos Big Sur
- oni2 v. 0.5.9-nightly | 0f1bf1ea (the same issue appeared on different builds in the last two weeks at least)

Logs: [trace.log](https://github.com/onivim/oni2/files/5874720/trace.log)

**Comment by bryphe** [comment]
Thanks for including the log, @DvirSadeh ! Was very helpful - I tracked down the issue to this configuration setting:

```
[INFO]  [ 0.470s] Oni2.Store.Vim : Running VimL from config: map <Enter> o<Esc>
```

It looks like the handling of `map` was incorrect, and in this case, it was running this binding when the command-line window was open - which would then cause the `o<Esc>` to be executed. This is a bug, since the `map` should only apply to normal/visual/select/operator pending modes.
