### ISSUE TITLE
Add "City Lights" as a Theme Option

### ISSUE THREAD

**Issue by markteekman** [onivim/oni2#3081]
A very pleasant looking dark UI which is currently available for Atom, Sublime and VS Code.
Would be a nice addition to the modern look and feel of Onivim 2's collection of themes :)

http://citylights.xyz/

Screenshot from their website:
![afbeelding](https://user-images.githubusercontent.com/3909046/106745482-70f52500-6621-11eb-96d9-86e1293a5be8.png)

**Comment by BenoitPingris** [comment]
Hey, you can install the vscode with oni and it will work!
Unfortunately this theme isn't accessible on https://open-vsx.org/ (the marketplace oni uses), so to install it you can `git clone` the city lights repo in `$HOME/.config/oni2/extensions/` (if you're on linux, for other OS I don't know which folder oni's using), then restart Oni and you can change your theme.

![image](https://user-images.githubusercontent.com/29386109/106764380-08657280-6638-11eb-860f-3caadc100c39.png)

**Comment by bryphe** [comment]
Oh ya, I like this theme a lot 😄 

It actually was published previously to open-vsx - but they had to tighten up the requirements (especially having a `LICENSE` defined in the metadata).

There's some issues being tracked on the city-lights repo in regards to getting it back on open-vsx:
- https://github.com/Yummygum/city-lights-syntax-vsc/issues/65
- https://github.com/Yummygum/city-lights-syntax-vsc/issues/66

I'll resolve this as 'external' since it is being tracked there. 

In the meantime, the workaround to `git clone https://github.com/yummygum/city-lights-syntax-vsx` into `$HOME/config/.oni2/extensions` that @BenoitPingris provided works great:

![image](https://user-images.githubusercontent.com/13532591/106800279-1bb31680-6615-11eb-990b-10b7dda97df0.png)

Thanks @BenoitPingris !

**Comment by markteekman** [comment]
Thanks @BenoitPingris for the workaround tip and @bryphe for the extra explanation on the topic! :) I'm going to try it right away!
