### ISSUE TITLE
Unable to close or switch from Changelog tab.

### ISSUE THREAD

**Issue by hosaka** [onivim/oni2#3107]
0.5.9-nightly
Ubuntu 18.04

Steps to reproduce:
- Launch oni2 (i'm using AppImage)
- With the default Welcome tab, open Changelog using Help->Changelog
- Attempt to switch or close the Changelog tab either using a mouse or keyboard.

Observed behaviour:
- Changelog tab will close and immediately re-open when trying to close it.
- Changelog tab will immediately be selected again when trying to switch tabs.
- Occasionally, when trying to close the tab, `:q`, middle mouse click and left click on `X` will cause no visible effect.

Expected behaviour:
- Changelog tab gets closed or remains in background when switching tabs.

**Comment by bryphe** [comment]
Hi @hosaka ,

Thanks for logging the issue!

This look like it may be the same bug as https://github.com/onivim/oni2/issues/3084 , which was fixed in https://github.com/onivim/oni2/pull/3088  (latest nightlies have the fix, now).

Just to double-check - which version of the nightly are you able to reproduce on? The commit id is visible on the welcome screen: 
<img width="365" alt="Screen Shot 2021-02-08 at 4 30 12 PM" src="https://user-images.githubusercontent.com/13532591/107298852-07af5080-6a2b-11eb-84f1-5300fd3d2eb3.png">

**Comment by hosaka** [comment]
Hi @bryphe 

Commit id is `bf928a0b`. Just switched to nightly `9aa3b88c`, everything is working! Apologies for the dupe issue and thanks for the quick reply!

**Comment by bryphe** [comment]
Excellent, thank you for the update @hosaka !
