### ISSUE TITLE
auto wrapping long text into multiple lines

### ISSUE THREAD

**Issue by advpetc** [onivim/oni2#3149]
I love writing some long text without changing to a new line, but it cause a small problem when I use oni2vim:

<img width="1132" alt="Screen Shot 2021-02-16 at 10 11 08 PM" src="https://user-images.githubusercontent.com/15725244/108155279-391bc200-70a4-11eb-929e-c666fc2fadf8.png">

-> this is what it looks like.

When I use viscode, it supports a nice auto wrapping for long paragraph:

<img width="896" alt="Screen Shot 2021-02-16 at 10 11 23 PM" src="https://user-images.githubusercontent.com/15725244/108155343-55b7fa00-70a4-11eb-9308-38017cc54be9.png">

Do you think a minor tweak would make it look nicer?

-- macOS big sur 11.2.1
-- oni2 0.5.9-nightly (0.5.1893)

**Comment by bryphe** [comment]
Hi @advpetc ,

Thanks for logging the issue!

We have a different default for word wrap (by default, `"editor.wordWrap"` is set to `false`). However... _both_ Vim and VSCode default to word wrap being on, so I think it would make sense for our default to be on, too.

Working on a fix to change the default here: #3161 - in the meantime, if you change your configuration to `"editor.wordWrap": true`, you should get that same experience, too.

One thing I noticed though is that, in your first screenshot, your font seems to be non-monospace - is that intentional, or was there a certain font you were trying to load? I'm just wondering if there is an additional bug in the font loading pipeline there

**Comment by advpetc** [comment]
Hi @bryphe,

Thank you for the fix. The change of configuration makes it work.

I also noticed the font issue. I haven't changed any default font from my config, so I guess they are still non-monospace? I recall a few month ago I seem to have the same issue: https://github.com/onivim/oni2/issues/1293. Not sure if they are somehow correlated, so just fyi.
