### ISSUE TITLE
Revery onBeforeQuit handler doesn't wait for async actions

### ISSUE THREAD

**Issue by timbertson** [onivim/oni2#3270]
👋    Hello, I've finally got Oni2 building through nix ([it's a long story](https://github.com/esy/esy/issues/972)). That's all still very fragile and not ready for prime time and not something you should support, so I'll try to limit my interactions to stuff that hopefully isn't caused by my weird build environment.

But I'm excited to be finally able to hack on Oni comfortably, so hopefully this is the first of many contributions 🤞 

I was trying to track down why Oni leaves behind an exthost process when it quits. I think it doesn't when things are running smoothly, so that's probably a bug in my particular setup that you shouldn't have to troubleshoot.

But the quit behaviour seems limited when revery initiates it. I can see that on `:q`, Oni quits nicely:

```
[DEBUG] [ 3.613s] Oni2.Store.StoreThread : Running effect: Batch:
 lifecycle.quitAll

[INFO]  [ 3.613s] Oni2.Store.dispatch : dispatch: ReallyQuitting
[INFO]  [ 3.614s] Oni2.Service_Syntax : Stopping buffer subscription for: 2
[DEBUG] [ 3.614s] Oni2.Syntax.Client : Sending close request...
[DEBUG] [ 3.614s] Oni2.Store.dispatch : After: ReallyQuitting
[INFO]  [ 3.614s] Revery.App : onBeforeQuit
[INFO]  [ 3.614s] Revery.App : Quitting
$
```

But when I just hit the window close button (on OSX), it's rather brief:

```
[INFO]  [ 2.137s] Revery.App : onBeforeQuit
[INFO]  [ 2.137s] Oni2.Store.dispatch : dispatch: (Quit true)
[DEBUG] [ 2.139s] Oni2.Store.dispatch : After: (Quit true)
[INFO]  [ 2.139s] Revery.App : Quitting
$
```

It seems revery exits the process immediately after running `onBeforeQuit`, which doesn't give the dispatches messages a chance to actually get executed:

https://github.com/revery-ui/revery/blob/26e8b737ec5a30a18754204960133dee1d04422a/src/Core/App.re#L65

In particular, this is never running ExtensionClientStoreConnector's quit action to clean up the extension host:

https://github.com/onivim/oni2/blob/39bb26f68040326ecf4d03f6c4428c05f13a02d5/src/Store/ExtensionClientStoreConnector.re#L28

---

I don't know revery well, but I'm guessing there are a few possible fixes:

 - oni could _synchronously_ do its quit actions to hold up revery (seems like a bad idea, may not be possible)
 - revery should let users disable its immediate quit mode (and take on responsibility for calling `exit(0)` when they're actually complete) through an explicit opt-in API
 - the function passed to `Revery.onBeforeQuit` could return some sort of lwt waitable rather than `unit`, so that revery knows to wait for this cleanup rather than just plowing ahead. That seems nicest, but might be inconsistent with the rest of the revery API.

I'd be happy to have a crack at actually fixing this, if you can provide some guidance on which direction is likely to be acceptable.

**Comment by bryphe** [comment]
Hi @timbertson ! :wave: 

>  Hello, I've finally got Oni2 building through nix (it's a long story).

Nicely done! That's quite an epic journey.

> But I'm excited to be finally able to hack on Oni comfortably, so hopefully this is the first of many contributions crossed_fingers

Awesome! Can always use the help :smile: 

> I don't know revery well, but I'm guessing there are a few possible fixes -

Seems like you have a really solid understanding - indeed, those are the options that were top of my mind too.

Some comments on each:

> oni could synchronously do its quit actions to hold up revery (seems like a bad idea, may not be possible)

We do have utilities that can accomplish this via [`LwtEx.sync(somePromise)`](https://github.com/onivim/oni2/blob/ecba53d423e4663f01778a5a1d25cc90fb4e369c/src/Core/Utility/LwtEx.re#L37) - it basically pumps the event loop while waiting for the promise to complete. So it's technically possible, but probably not the best experience if we need to render some UI while closing, because it would stop the UI from re-rendering. If we've already closed the window, though, and we're just waiting for some other processes to close - might be acceptable. 

> revery should let users disable its immediate quit mode (and take on responsibility for calling exit(0) when they're actually complete) through an explicit opt-in API

This sounds reasonable! We could alter the `onBeforeQuit` API to take a function that cancels the quit, ie:

```
Revery.App.onBeforeQuit((cancelQuit) => {
    cancelQuit()
});
```

Or, potentially, a return value:
```
Revery.App.onBeforeQuit(() => {
  // BlockQuit
  AllowQuit
});
```
The latter would require some tweaks to the way that event is subscribed (because there can be multiple quit handlers - we'd need to dispatch all of them and only allow quitting if all them report `AllowQuit`).

If we had this API, we could record that the user was intending to quit, block it, and then quit ourselves as you suggested. This seems pretty nice :+1: 

> the function passed to Revery.onBeforeQuit could return some sort of lwt waitable rather than unit, so that revery knows to wait for this cleanup rather than just plowing ahead. That seems nicest, but might be inconsistent with the rest of the revery API.

This would be nice as well. Unfortunately, the Lwt engine isn't fully integrated with Revery - so there might be cases where this wouldn't work as expected (using Lwt primitives that depend on a running engine - they might not complete).

From my perspective - the second option you mentioned seems like the most straightforward to integrate today. I would love to see that warning go away on quit! :smile: 

Thanks for the thorough and thoughtful investigation, @timbertson !

**Comment by timbertson** [comment]
Thanks for the helpful response, I've taken an initial go in https://github.com/revery-ui/revery/pull/1053. With that approach, the changes are reasonably minimal:

https://github.com/onivim/oni2/compare/master...timbertson:quit-consistently

Interestingly it's kicking the can down the road a _bit_, if any of oni's own QuitCleanup actions are asynchronous then you get the same problem. But at least that's internal to oni2 now, and I don't think there is anything async.
