### ISSUE TITLE
Quick open requires exact match?

### ISSUE THREAD

**Issue by lougreenwood** [onivim/oni2#3278]
It seems that it's not possible to use quick open to search for fragments of a file name.

For example, given a file name `my-thingy.js`, if I perform a quick search for `my thingy`, no results are found.

However, `my-thingy` will find the file.

**Comment by CrossR** [comment]
Ah! Right now, the quick open doesn't filter out/do anything smart with the query you give, outside of "smart" search (a lower case query is treated as case insensitive, but include any upper case and it is treated as case sensitive).

That means when you search for `my thingy`, you are looking for a file with a ` ` (space) character in it, which doesn't exist. Right now, I'd recommend just omitting the space, and any other dashes etc, `mythingy` should find the correct result, and you can experiment with shorter searches too (maybe `mthin` works or `mtjs` etcetc. My first short search is almost always fine, and the few times its not I learn in the repo what I need.).

I am looking at adding the space based filtering that VSCode has, but haven't got it fully added yet. We could also just add some form of filtering on the query, but that would probably cause more issues than it fixes.

(You can also see the docs and/or test out the fuzzy finding with the repo over here, since we utilise the `fzy` project to power the search: https://github.com/jhawthorn/fzy/blob/master/ALGORITHM.md).

**Comment by lougreenwood** [comment]
#3487 fixes this, so will close
