### ISSUE TITLE
Weird shadow when using "larger" files, :term and splits

### ISSUE THREAD

**Issue by iilonmasc** [onivim/oni2#3328]
When using splits in combination with files exceeding the window size and a theme which sets the `:term` background color the UI looks a bit "wonky" having shadows on the split with the large file and no shadows on the split with the small file.

The theme I use is gruvbox-dark-soft.

I made a screenshot (blurred the code though), on the left is a file with only 22 LOC and on the right a file with more than the current window size can show. The bottom split is a regular `:term` (runnning k9s if anyone's interested)

![Screenshot 2021-03-25 141744](https://user-images.githubusercontent.com/22161944/112479273-2b2d2100-8d75-11eb-8133-2d961f279065.png)

**Comment by kinglouie** [comment]
I think this is by design, the shadow is an indicator that the buffer can be scrolled, you also get this shadow on horizontal overflow. When looking at vscode the horizontal shadows are more subtle and there is no noticable bottom shadow which I think looks better then onivim. vscode only shows vertical shadows on the top when scrolled down.

**Comment by iilonmasc** [comment]
Oh you're right! I checked in VSCode and also checked horizontal overflow in both. Since this is no real issue I'll close this
