### ISSUE TITLE
Program starts halfway between two screens

### ISSUE THREAD

**Issue by nathanjwtx** [onivim/oni2#3349]
I have a 3 screen setup; 2 monitors and laptop screen. Onivim continually opens across one monitor and the laptop screen. I've tried all sorts of usual fixes for programs opening offscreen but nothing sticks. Any ideas?

Windows 10 Pro
Lenovo ThinkPad
BenQ monitors
Onivim v 0.5.2007

**Comment by bryphe** [comment]
Hi @nathanjwtx ,

It sounds like we might be persisting incorrect window coordinates - when the window moves, we store the position and size in the `%LocalAppData%/Oni2/store` folder (for example - mine is `C:/Users/Bryan/AppData/Local/Oni2/store` - you could try renaming or delete that folder to see if that's the issue.

It'd be interesting to see if it still opens in the wrong spot after doing that.

I'd be curious as well - how are you opening Onivim? Is it via the terminal, or start menu?

**Comment by nathanjwtx** [comment]
Hi @bryphe 
I tried deleting the folder as suggested but it still opens as before; half on screen 2 (monitor) and half on screen 1 (laptop).

I am opening it from the Start Menu.

**Comment by nathanjwtx** [comment]
It also doesn't remember the previous app window size.

**Comment by lemerchand** [comment]
Let me also chime in on this as well! I have the same issue, but even further, when I maximize Oni it spreads beyond (albeit ever-so-slightly) beyond the screen it's on.  I'm posting here instead of a separate thread since it might be related.

Here is a screen shot. It is a bit difficult to see, but if you look at the edges of Oni you'll see where it spills over onto the other displays.  

![image](https://user-images.githubusercontent.com/72176216/113172681-8049b680-91fd-11eb-922a-052b64c603d2.png)

**Comment by nathanjwtx** [comment]
I get that too. Looks like a thin white line on the edge of the other screen.

**Comment by Apostolique** [comment]
Related issue: #1893
