### ISSUE TITLE
File explorer did not reload automatically

### ISSUE THREAD

**Issue by polotto** [onivim/oni2#3350]
Hi,
first congratulations for the project, I became Patreon and I enjoining the editor.

I discovered an odd behaviour: the file explorer didn't update when I add new file or folder. I'm running on MacOS.

Thanks,
Polotto.

**Comment by lemerchand** [comment]
If I recall correctly, they haven't implemented a filesystem watcher so for now it seems it must be refreshed manually. Try `:cd ..` out of the dir and `:cd` back into it

**Comment by keeslinp** [comment]
I have found that closing and re-opening the folder makes it appear.

**Comment by polotto** [comment]
Thank you to make it clean. I'll use that work around until watcher be implemented.

**Comment by bryphe** [comment]
@lemerchand @keeslinp - thanks for the workarounds! Yes, indeed - we need to get our file watcher wired up

Related #3350

**Comment by jerabaul29** [comment]
This issue is logged quite many time :) .

I understand that a full upgrade / overhaul of the file explorer is a lot of work, and that other things may have higher priority, so I was wondering: @bryphe , do you think it may be reasonable to set up a 'poor man's fix' here, for example, refresh the tree (maybe only the 'visible' part of it to save a bit of CPU) once or twice a second when it is visible? I suppose this would 'fix' the problem from a user point of view, while waiting for a more fundamental solution :)

**Comment by jerabaul29** [comment]
And I guess it is well possible that it is not that much of a poor man's fix anyways, as I guess this will anyways be the only way to find out file tree changes that are induced from outside of the editor? (I.e. guess there could be automatic update when a command modifying the file tree is called from onivim, so that it happens instantly, but that in addition one will always need a 'lower frequency' refresh?).

**Comment by bryphe** [comment]
Unfortunately I'm not sure there is a quick fix, but I'm working on a fix that includes a `Reload` command as well as integration with the file system watcher in #3365 . 

We could tap into a buffer saved event, too, but I think the file watching strategy will be more general. I recall there were some issues we hit where the file watching just stopped working (https://github.com/aantron/luv/pull/55).  If there are bugs with the file watcher, #3365 will at least make it easier to implement a timer-based stopgap solution like you suggested. 

> This issue is logged quite many time :) .

Indeed, I sure would be happy to have this unblocked!
