### ISSUE TITLE
100% cpu on new filewatcher feature

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#3373]
I was testing out the new filewatcher feature and it was working fine at first but after a while the editor froze with 100% cpu. I don't know how to reproduce yet so I wanted to provide a debug trace file. As soon as I started logging to trace the editor froze up with 100% cpu and the tracefile is 200mb of this:

`[INFO]  [50.304s] Oni2.Service.OS : Luv.stat: /home/dummy/onivim2-trace.log`

it seems this is a feedback loop where oni logs a line to trace file for every line created in trace file.
As soon as the issue with the trace file is fixed I will try to reproduce the original issue.

**Comment by bryphe** [comment]
Thanks for testing the new file watcher out, @KingEdwardI !

> after a while the editor froze with 100% cpu. I don't know how to reproduce yet so I wanted to provide a debug trace file.

Ouch... what sort of project were you working on? JavaScript / TypeScript / etc? Do you recall what sort of action preceding the freeze (saving, expanded a node in the explorer)?

I'm running with the setting on all my machines so hoping I can reproduce

>   it seems this is a feedback loop where oni logs a line to trace file for every line created in trace file.

Ouch, ya, you were exactly right on the log issue - working on a fix for that in #3374 (also makes the file watcher more efficient in general - there were several cases were were stat'ing when we didn't really need to do so). 

Hopefully once #3374 is in we can get the log and get more clues on the root cause.

**Comment by bryphe** [comment]
Hi @kinglouie - have you hit this at at all again?

**Comment by kinglouie** [comment]
@bryphe nope, feel free to close this :)
