### ISSUE TITLE
Keybindings with CTRL and SHIFT are very slow in execution

### ISSUE THREAD

**Issue by StephanRoemer** [onivim/oni2#3392]
I have this entry in my keybindings.json:
`{ "key": "<S-C-J>", "command": ":pu! _", "when": "normalMode" }`

When pressing CTRL+SHIFT+J it will insert a blank line above the cursor.
However, when executing the shortcut, it takes about 2 seconds until the 
action is executed.
The same action mapped to CTRL+J works as fast as expected.

**Comment by bryphe** [comment]
Hi @StephanRoemer ,

It sounds like the input may be thinking there is the possibility of another action - for example, if there is another keybinding like `<S-C-J>k`, the input system would wait until the `vim.timeout` setting (default - 1second).

There is a not-very-polished debug view we can use for this:
- `Control+Shift+P` -> `Debug: Show input state`

Then, running the `<S-C-J>` command might give a clue if it's waiting for another key - if so, it'll show `Control+Shift+J` under 'Consumed Keys':
![2021-04-09 15 16 20](https://user-images.githubusercontent.com/13532591/114246153-bea24c80-9946-11eb-8c51-0dcc4a6d94bb.gif)

We might be able to narrow it down at your keybindings, too -

We do need a better UX for cases where we're waiting on an extra key press, if that is the issue here

**Comment by StephanRoemer** [comment]
I just checked, funnily, it works flawlessly now. Also, the shortcut doesn't appear in "Consumed". I think I closed and re-opened Onivim in the meantime and that fixed it.
Silly me, that I didn't try that before. I'll close this report for now.
