### ISSUE TITLE
:bn and :bp crash omnivim

### ISSUE THREAD

**Issue by iamcodemaker** [onivim/oni2#3543]
I've seen some inconsistent behavior here, so I'm not quite sure what causes this, but right now I can reproduce it by opening onivim2 and running `:bn` or `:bp`. On v0.5.0

**Comment by bryphe** [comment]
Thanks for reporting, @iamcodemaker !

Unfortunately I'm not able to reproduce this... maybe some extra info will help:
- What platform are you using? Mac/Windows/Linux?
- Do you have any other files open, or are you able to reproduce immediately after opening and running `:bn` or `:bp`?
- Does it reproduce on a newer build? Either the stable (`0.5.5`) or nightly? It's possible it's fixed by a PR that has come in since `0.5.0`, like https://github.com/onivim/oni2/pull/2351

**Comment by iamcodemaker** [comment]
I'm on Mac. I was able to reproduce this by running onivim2 and then immediately running `:bn`. I'll test with 0.5.5.

**Comment by iamcodemaker** [comment]
Unable to reproduce on 0.5.2120

**Comment by bryphe** [comment]
Thanks @iamcodemaker for checking in latest 👍
