### ISSUE TITLE
Feature Request: Add gt and gT as default keybindings

### ISSUE THREAD

**Issue by tristil** [onivim/oni2#3673]
In Vim `gt` and `gT` cycle through tabs. Can these be added as default keybindings in Oni 2 as well? In addition can the behavior be changed so that when you reach the last (rightmost) tab it will cycle back to the first (leftmost) tab?

**Comment by mabuchner** [comment]
If you enable "Vim tabs" then this already works

```json
 "oni.layout.singleTabMode": true,
"oni.layout.layoutTabPosition": "top",
```

**Comment by tristil** [comment]
Interesting! Thanks.

**Comment by tristil** [comment]
Hmm... I'll have to play around with this a little, but I had gotten used to the default way Onivim handles tabs. For example, selecting a file adds it to the group instead of replacing the current file.

**Comment by tristil** [comment]
In general I'm super unclear about the two different modes. It would be nice if there was something in the documentation about it.

**Comment by mabuchner** [comment]
It's briefly mentioned in the documentation [here](https://onivim.github.io/docs/getting-started/vim-tips#how-do-i-get-the-tabs-to-behave-as-they-do-in-vim).

Yes, it's a bit of a chore to use Vim tabs right now and #2232 + #564 is actually the reason why I'm not using Oni2 for my daily work.

**Comment by CrossR** [comment]
> In general I'm super unclear about the two different modes. It would be nice if there was something in the documentation about it.

I can look at expanding the documentation around this, but there is two (conflicting) models of tabs:

 - Vim style - In vim, a tab is more of a workspace / a layout (I've seen some discussion that a tab in vim shouldn't really be called a tab at all, more of a "viewport"). Its a view over a number of buffers. So it could contain 1 buffer, or it could contain 3 buffers, say all aligned next to each other. You could then move to another tab, and have a different layout of buffers there etc. 

 - "Modern" style - In more "modern" editors, usually a tab is just a buffer, so one tab = one file. There isn't any concept of storing layouts together etc, you just have one tab = one file. VSCode etc all obviously still do have splits and such, but you have "splits of tabs" (instead of "tabs of splits" in vim). That is, whereas in vim if you moved from tab 1 to tab 2, you could move to an entirely different layout (say three buffers on top of each other, to three buffers next to each other), VSCode doesn't have that. VSCode instead has the ability to change files inside of a single split, but not to move to an entirely different layout, just from swapping tabs.

As to which of those is most useful / most intuative to you, I'm not sure! I would say the major downside/point of confusion about the vim style of tabs is that you could open up five files and end up with only 1 visible on screen, which is confusing if you don't know they are just hidden. Whereas in the "modern" style of tabs, if you open 5 files, you get 5 tabs and its all very obvious. The downside of the VSCode style is more obvious, that if you like or find it useful to have different layouts of splits, you can't easily do that.

I find both have their use (I use the default style for Oni2, just so I'm using the way that most people start out with it set, so its easier to debug people's issues), so which you find best will depend.

Oni2 does have some things that are still needed to make it slightly easier to work with vim-style tabs, such as easier ways of selecting "current tab/new tab/vsplit/split" for opening files and such. Getting that feature added should help the usability of them a lot.
