### ISSUE TITLE
Line number isn't displaying correctly when scrolling

### ISSUE THREAD

**Issue by thangngoc89** [onivim/oni2#374]
So I notice this behaviour when scrolling up and down.

given a file with 10 lines and the cursor is on line 5, the line numbers are displayed like this:

```
1 2 3 4   5    6 7 8 9 10
4 3 2 1 ->5<-  1 2 3 4 5 
```

Gif:

![](https://media.giphy.com/media/ckHvsqcVPOPF97VPoZ/giphy.gif)

**Comment by tcoopman** [comment]
The default configuration is for `relative` lineNumbers. You can change this in the configuration file to `absolute`.

**Comment by CrossR** [comment]
Yeah, this is a feature of Vim, to aid the use of macros/operations with line numbers (ie doing `11j` is much easier with relative line numbers, though its a different argument if you should be doing that in the first place).

We should definately swap it to absolute by default though, since its hardly the expected behaviour for most people.

**Comment by thangngoc89** [comment]
@thangngoc89 @CrossR  Thank you for clarifying this to me. I still don't understand why this is a useful feature anyway?

**Comment by szbergeron** [comment]
@thangngoc89 it helps in visual mode to do jumps by a specific number of lines since you can't easily jump to a specific line number. It just means you can see what number to prepend to a movement rather than having to to arithmetic on the fly.

**Comment by thangngoc89** [comment]
@szbergeron ah. thank you for explaining this to me. I'm such a noob :D .
