### ISSUE TITLE
Remove need for ONI2_NEOVIM_PATH environment variable

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#40]
We require setting an `ONI2_NEOVIM_PATH` variable as described in #35  , just so the binary can figure out where the vendored binaries are. Not ideal and always a pain to set up.

I'd like to add an `esy bootstrap` command that is run after `esy build` - this would generate a JSON or TXT file with the paths to the vendored binaries for development. Then, the executable would pick these up on initial run (our installers would also generate this, or a release build could simply figure out the relative path to the vendored binaries based on our install layout).

Note that we'll need to vendor a couple more binaries:
- `node`
- `ripgrep`?

So whatever solution we come up with will need to be extensible to those binaries too.

**Comment by Akin909** [comment]
@bryphe I started looking at putting together a small shell script to do this since I figured that would be a universal way to do this, without requiring a language dependency like a node script, although since if this is maybe happening when we create builds prior to release would it be safe to assume that node or ocaml are installed (could use ocaml, but then you'd need to build that program into an executable :laughing:).

Would a shell script work on windows? (I really haven't used a windows machine in a *very* long time hence the questions)

**Comment by bryphe** [comment]
Sweet, thanks for looking at this, @Akin909 !

My hope is that - for release - we'll have a determined directory layout (ie, a `vendor` folder at the root), so we can fallback to that layout. In other words, we wouldn't need this for release builds.

For development, though, we'll need some help figuring out where that `vendor` folder is. A shell script should be fine - `esy` comes with a `bash` shell for Windows.

**Comment by bryphe** [comment]
Fixed by #43 ! Thanks @Akin909
