### ISSUE TITLE
Handle (white)space in command mode autocompletion

### ISSUE THREAD

**Issue by Samonitari** [onivim/oni2#434]
Autocompletition in command mode doesn't handle etries with spaces correctly.

1.  When dropping a filesystem based suggestion (in favour of another one: ie, choosing another) for command (`e`, `chdir`) parameters, only the last word (or Word?) gets deleted.
![command_mode_space_bug](https://user-images.githubusercontent.com/15932551/61203868-e621a200-a6eb-11e9-8c1d-3adad0c4a245.gif)
The command mode's state machine should delete the currently selected completition entry when a discard transition occours.

2. When selecting an entry with spaces, it doesn't get escaped (like it did in Oni), and argument will be invalid for the command - for example chdir fails to folders with spaces in them (on Windows at least)

**Comment by manuhornung** [comment]
1. The wrong insertion is probably caused by the fact that we determine the position at which to insert the autocompletion by going backwards through the entered string and looking for the first space we find. See https://github.com/onivim/oni2/blob/3fb7276cdef066316caaf08ab7822c5f9a719567/src/editor/Core/Utility.re#L112
(bryphe provided me with this insight :) )
I'm not sure if this is the logic we want - are there commands that include multiple spaces which are not part of a path? Otherwise we might be able to just take the first space instead?
FWIW, original vim keeps track of the autocomplete starting point itself and doesn't retroactively calculate it. It might be necessary that we do the same, see `xp->xp_pattern` in https://github.com/onivim/libvim/blob/07e5aa155c887b8efbe023544c26f680a221abf1/src/ex_getln.c#L5556

2. About the missing escaping: We seem to use `vimCommandLineGetCompletions` from libvim, which in turn directly hooks into `expand_cmdline`. The native vim flow has a lot of complexity around it which also makes sure that things like `~` are retained correctly in the suggestions, unnecessary prefixes are left out and other variables are expanded. This is more understandable by comparing screenshots:
Native vim
![image](https://user-images.githubusercontent.com/4516798/62247446-23717980-b3e6-11e9-86cb-e0dc85caec1f.png)

Oni2
![image](https://user-images.githubusercontent.com/4516798/62247487-38e6a380-b3e6-11e9-9cbb-6d8fb293ade7.png)

Some of these things seem to happen inside `showmatches` after `expand_cmdline` in the native flow - I think we might need to add these steps in a similar form to our `vimCommandLineGetCompletions` to get the same behavior. I'm unsure which parts exactly though since I can't quite figure out where exactly the escaping etc. happens. Will need some more investigations and drawing things up to figure this out.

**Comment by Samonitari** [comment]
> 1. I'm not sure if this is the logic we want - are there commands that include multiple spaces which are not part of a path? Otherwise we might be able to just take the first space instead?
>    FWIW, original vim keeps track of the autocomplete starting point itself and doesn't retroactively calculate it. It might be necessary that we do the same

I thought almost this when I said "The command mode's state machine should delete the currently selected completition entry when a discard transition occours."
I meant to say (quite clumsily), that if you keep track of the currently selected autocompletion entry you can remove it accurately too. But the reason behind it was sane - do NOT try to calculate (guess) the point after-the-fact, but store some information when choosing an entry.

Quite possibly choosing the vim approach (store the starting point) is better, as not un

I thought about implementing this, as this seemed a possibly good first issue but: I do not know Reason.
Maybe if you think the first part can be solved as a stand alone issue, I'll give it a shot.

**Comment by bryphe** [comment]
Issues 1) and 2) called out at the root issue should be fixed with #2005 

However, the escaping didn't seem necessary in my testing - let me know if you have case that is failing w/ the latest that I can try.

**Comment by Samonitari** [comment]
On first skimming, it seems fine!
I plan to spend some more time with oni2 in the weekend though, so I'll report if I've found some missed parts!

**Comment by bryphe** [comment]
Great news! Thank you @Samonitari

**Comment by Samonitari** [comment]
Unfortunately there is still a quirk.
Issue 1) is fixed,
Issue 2) is half okay - on linux I won't get autocompiletion of the contents, if I select a folder with whitespaces in its name.
On Windows this doesn't seem to happen

**Comment by Samonitari** [comment]
I just checked this after reporting #3751, and this has been fixed since some time ago.
Original sub-issue 2) is gone on linux also.
