### ISSUE TITLE
Splits: Handle Rotation

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#439]
Example: ctrl-w r
Expected result: splits rotate
Actual result: nothing happens

Related actions: ctrl-w L, ctrl-w J, etc

**Comment by bryphe** [comment]
We're still missing the rotation actions from the `libvim` layer (so that the Vim keybindings would trigger this behavior), but we could still potentially start on the logic here, by also implementing it as a command available in the command palette:

__Part 1: Add a `rotateForward` and `rotateBackward` method to `WindowTree`__

The first part of this work would be figuring out how to implement the rotation logic, given a target split id (`int`) and a current window tree [`WindowTree.t`](https://github.com/onivim/oni2/blob/master/src/editor/Model/WindowTree.re)

Could be called as follows:
```
// Find the parent split container containing split 1, and rotate it -> move the head to the tail
let newWindowTree = WindowTree.rotateBackward(1, windowTree)
```

The `WindowTree.t` type is defined here: https://github.com/onivim/oni2/blob/8037062c3edbd818b817ef0543f8bc7beb342a8b/src/editor/Model/WindowTree.re#L18

And we'd need to implement a recursive method that finds the `Parent(direction, children)` where `children` contains the target window split ID. When we find that ID, we'd implement the rotation logic on its children.

__Part 2:__ Add a command to the Command Palette and hook up to reducer

Next, once we have that logic, we'd need a way to invoke it. We could add a command to the `CommandPalette` like: https://github.com/onivim/oni2/blob/master/src/editor/Model/CommandPalette.re

- we could use commands like `Actions.Command("view.rotateForward")` and `Actions.Command("view.rotateBackward")`

With the commands and the logic implemented in Part 1, we could wire it up in the window reducer here: 
https://github.com/onivim/oni2/blob/8037062c3edbd818b817ef0543f8bc7beb342a8b/src/editor/Store/WindowsStoreConnector.re#L94

The `windowManager` state contains both the windowTree (`windowManager.windowTree`)and the currently selected split (`windowManager.activeWindowId`) - so we'd have all the context we need to pass to the functions we implemented in Part 1.

Once this is wired up, we should be able to open the command palette and rotate splits forward or back.

**Comment by bryphe** [comment]
(scoping this issue to just the rotation aspect for now)

**Comment by KevinSjoberg** [comment]
I’d be happy to take a stab at this. 🙂

**Comment by bryphe** [comment]
Sweet, thank you @KevinSjoberg ! Assigned it over -

**Comment by KevinSjoberg** [comment]
@bryphe would you mind explaining this sentence a bit further?

> We're still missing the rotation actions from the libvim layer (so that the Vim keybindings would trigger this behavior), but we could still potentially start on the logic here, by also implementing it as a command available in the command palette

I understand we're using `libvim` for managing and manipulating buffers, but the lines are blurry at times. What part of this feature will be handled by `libvim`? I assume rotating the windows classify as UI and should therefore be handled exclusively by Oni2.

Is code required within `libvim` in order for `c-w r` to trigger the actions I set out to create in this pull request?

**Comment by CrossR** [comment]
I think @bryphe is saying there is technically two parts to this:

 - Hook up the Oni2 end of physically doing the rotation etc, which is outlined in the issue.
 - Hook up `libvim` such that when the user triggers a rotation with a key bind (be it the default or not) we get a notification sent to Oni2. That would then let us rotate with vim binds (or any remapped binds too! Anything that triggers the rotate on the vim end), rather than a command palette option.

You can start with just the Oni2 side of things, so you'd want to end up with some commands that sit in the command pallets (Ctrl-Shift-P menu) that let you rotate the view. Then, we can look at hooking those commands up to `libvim` by updating `libvim` to notify us on those events.

**Comment by KevinSjoberg** [comment]
Thanks, @CrossR. That was super helpful. I have a much better understanding of how things correlate. 🎉

**Comment by KevinSjoberg** [comment]
I've been playing around a bit more with the window tree to enhance my understanding.  I assume the `WindowTree`, or more accurately, the `t` type represents some tree data structure. I tried visualising how that window tree is being built as I create splits using the following function.

```reason
let rec logTree = (tree, ~level) =>
switch (tree) {
| WindowTree.Parent(direction, children) =>
    let stringOfDirection = direction =>
    switch (direction) {
    | WindowTree.Horizontal => "horizontal"
    | WindowTree.Vertical => "vertical"
    };
    let space = String.make(level, ' ');
    Log.info(space ++ "Parent (" ++ stringOfDirection(direction) ++ ")");
    List.iter(logTree(~level=level+2), children);
| WindowTree.Leaf(_) =>
    let space = String.make(level, ' ');
    Log.info(space ++ "- Split")
| WindowTree.Empty => ()
};
```

I then modified

https://github.com/onivim/oni2/blob/8b2e55c83e33c6e1c862efe3dd945c853b68e08e/src/editor/Store/WindowsStoreConnector.re#L135

to print out the current tree every time I split a window.

```reason
| AddSplit(direction, split) => {
    let state = {
        ...s,
        windowManager: {
        ...s.windowManager,
        activeWindowId: split.id,
        windowTree:
            WindowTree.addSplit(
            ~target=Some(s.windowManager.activeWindowId),
            direction,
            split,
            s.windowManager.windowTree,
            ),
        },
    };
    logTree(state.windowManager.windowTree, ~level = 0);
    state;
  }
```

Given the following window layout

![Screenshot 2019-08-05 at 11 16 27](https://user-images.githubusercontent.com/503025/62453391-852d3d00-b772-11e9-8282-39f02f539c4b.png)


It prints out the following tree.

```
[INFO] Parent (vertical)
[INFO]   Parent (horizontal)
[INFO]     Parent (vertical)
[INFO]       - Split
[INFO]       - Split
[INFO]     - Split
[INFO]   Parent (horizontal)
[INFO]     - Split
[INFO]     - Split
```

I've replicated the same layout within in Vim and ran the `c-w r` and `c-w R` accordingly. I've noticed the following things:

- You can only rotate splits directly nested under a single parent. E.g, it's okay to rotate `a` and `b` but not `c`. You can't rotate a split that is adjacent a `Parent`.

- In Vim, if you try to rotate an invalid split, you're greeted with the message `E443: Cannot rotate when another window is split`. Do we want to replicate that behaviour as well?


Any thoughts?

**Comment by bryphe** [comment]
Thanks for the detailed investigation, @KevinSjoberg ! Good idea to log out the tree structure (and try it in Vim!)

> You can't rotate a split that is adjacent a Parent. This might have been obvious from the beginning but it wasn't to me.

I wondered why this was the case, actually... It makes sense to me that rotation would be scoped to a particular parent, but would it be a problem to rotate the `Parent` in the list of splits?

> In Vim, if you try to rotate an invalid split, you're greeted with the message E443: Cannot rotate when another window is split. Do we want to replicate that behaviour as well?

I'd be OK either way - implementing rotation to include Parents (so no error message, but the rotation completes), or showing an error message. I'm not an expert on the rotation behavior - do you know if there is a good reason to block it in that case?

I tried poking around a bit at the Vim source code where it does that check: https://github.com/vim/vim/blob/1417c766f55e5959b31da488417b7d9b141404af/src/window.c#L1688 but couldn't find the reason for adding that check 🤔

**Comment by KevinSjoberg** [comment]
I guess we can close this one? If I'm not mistaken we have a different issue tracking the extended behaviour.

**Comment by bryphe** [comment]
Sounds good to me @KevinSjoberg ! Window rotation is fully implemented now - thanks for your work on it 👍 We'll track other window split management work in other issues.
