### ISSUE TITLE
A or I in Visual Mode only apply to one line

### ISSUE THREAD

**Issue by ataulien** [onivim/oni2#471]
I noticed that Oni2 crashes when you try to add some text to line starts or ends when in visual mode.

How to reproduce:

 1. Enter some text
 2. Press V to select it
 3. Press A or I
 4. (Oni2 hangs and crashes)

I expected to be able to enter text to get appended to the start (or end) of the selection.

The type of visual mode does not seem to matter. It crashes when selecting only a part of a line using `v`, it crashes when selecting whole lines via `V` and also in block selection mode via `C-v`.

I have used the windows artifacts built by Azure for commit b4774d6.

**Comment by bryphe** [comment]
Thanks for reporting, @ataulien !

I checked this out and we're hitting a blocking-input mode (it's hitting a codepath in libvim that hasn't been updated to be non-blocking) - working on it here: https://github.com/onivim/libvim/pull/149

**Comment by pkariz** [comment]
It doesn't seem to stuck now, but there is another problem with visual mode insert, example:
1. `ctrl + v`
2. select a few rows
3. press `I`
4. type whatever
5. hit escape to go to the normal mode

the result is that the change is applied only to the last line instead of to all selected lines (+ at the start of the last line, not where you actually pressed `ctrl + v`).
Also if it helps, the visual selection is acting weird when you are selecting rows, for example in this file:
```
eval expr = case expr of
    AND (F::_) -> F
```
where the second line is indented with a `tab`, if you press `ctrl+v` on `A` in the second line and then press `k` to move up then the highlight will be incorrect

**Comment by n111k** [comment]
Visual block append seems to suffer the same behavior @pkariz identified for insert operations.

Example (Onivim2 eb24c72 on Windows 10):
![onivim2_vis_blk_append](https://user-images.githubusercontent.com/60955055/77857473-82c09d00-71b2-11ea-874d-88f73ff2b085.gif)

Reference Behavior (Onivim 0.3.9 on Windows 10):
![onivim_vis_blk_append](https://user-images.githubusercontent.com/60955055/77857667-c962c700-71b3-11ea-9cd9-8711f9556bf8.gif)

**Comment by bryphe** [comment]
FYI, this should be fixed now with https://github.com/onivim/oni2/pull/3011

Feel free to open a new issue if there is still missing functionality here -
