### ISSUE TITLE
Zen Mode: Single-file mode

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#495]
This is actually @manuhornung 's idea:

---

Apart from full IDE experience, there's also a use case for quickly opening, editing and closing a single file. It always felt unnecessary and overwhelming to me to show that file in a full-fledged IDE window. I'd rather have a simple buffer view without a file explorer or any other sidebar, tabs etc. For that case. Also opening it as a new buffer in an existing window seems confusing to me.

---

I think this would be a pretty cool setting to have. Onivim 2 starts up fast compared to my other editors that it makes sense to use it in this single-file capacity.

#### Part 1 - Add Configuration Value

We'd need to add a `zenModeSingleFile` setting to our configuration value type here:
https://github.com/onivim/oni2/blob/19de6c6fa1a4b7aff19272eaa0bab0b64624f8e0/src/editor/Core/ConfigurationValues.re#L15

I think probably we'd want to default this to `false` - but I'm open to ideas.

#### Part 2 - Add Configuration Parser

Next, we'll need to a parser to pick up the value of `zenMode.singleFile` from the JSON configuration. That can be added here:

https://github.com/onivim/oni2/blob/19de6c6fa1a4b7aff19272eaa0bab0b64624f8e0/src/editor/Core/ConfigurationParser.re#L132

#### Part 3 - Hook up setting

The trickiest part is the 'wiring' up of this setting. We need to know:
1) The value of  `zenMode.singleFile`
2) The number of files the user specified

And then, when we load the configuration, check the value of `zenMode.singleFile` + the number of files, and turn on Zen mode if necessary.

We parse the CLI early here:
https://github.com/onivim/oni2/blob/ac6951508f3555ce9420ad14ba5ee651533ddf50/src/editor/bin_editor/Oni2_editor.re#L19

And we load the configuration here:
https://github.com/onivim/oni2/blob/ac6951508f3555ce9420ad14ba5ee651533ddf50/src/editor/Store/ConfigurationStoreConnector.re#L47

I think the best place to handle this logic would be in the `ConfigurationStoreConnector`. We'll need to plumb the CLI information from that `Oni2_editor` -> `StoreThread` -> `ConfigurationStoreConnector`. Then, on the _first_ load of the configuration, we check that `zenModeSingleFile` value against the number of files specified - and if we need to actiave zen mode, we can dispatch the `ToggleZenMode` action.

**Comment by TheSpyder** [comment]
That seems like it should be true by default, encouraging use of oni2 as the system default EDITOR setting 🤔 especially if it’s opening a new oni2 and not trying to reuse instance windows 🤔

And, imo, if I execute oni2 at the command line with a few files I’d be fine with hiding the folder tree and just showing tabs - but I guess that’s not really what zen mode is.

**Comment by Cy-Tek** [comment]
I personally wouldn't want my other tabs hidden just because I opened one new file. I often am working on a project and need to quickly edit a file from a different project. That could be rather annoying if there wasn't a way to quickly get back to the other tabs I had opened. I do like the idea though of opening a single file in zen mode, just want to make sure there's a good way to get back to the project file tabs that were opened easily as well.

**Comment by TheSpyder** [comment]
I didn't mean hide existing tabs - I was talking about this single file mode which will open a new instance of Oni2 (or perhaps a new window in the existing instance).

**Comment by Cy-Tek** [comment]
I'm sorry, my mistake :) I understand what you're going for now 👍 I think that's a great idea!

**Comment by manuhornung** [comment]
I think you asked some relevant questions here, @TheSpyder :
:one: what do we do if the user opens multiple "single files" at once?

:two: what do we do if they open several single files using subsequent commands?

I can think of two paradigms:
:a: one oni2 window per `oni2` command (also `oni2 .`) - this would open the files from :one: in a single window with multiple tabs but each file from :two: in a separate window. Probably rather easy to understand. Might end up with a lot of windows if one tends to open many single files in succession - too many? 
:b: one oni2 window per opened folder *plus* one catchall window for single files. Basically `oni2 .` would always open the full IDE view while `oni2 myfile` would open a new window in zen mode. All subsequent single file calls would then open a new tab in that window instead of opening another one. This might create less clutter but could also be hard to understand, what do you think?
(Still no file explorer there because it would be misleading - we have an arbitrary set of files from potentially completely different paths here.)
