### ISSUE TITLE
Set Syntax to HTML does nothing on Svelte file

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#497]
I opened a Svelte file and Oni2 shows it as plaintext. Trying to run `:set syntax=html` does nothing at all.

**Comment by CrossR** [comment]
I assume this is because we don't use the vim syntax highlights, but also we don't use the vim filetype, and instead its all done via textmate highlights.

I guess there is a few options here; We could update the libvim side to send us some form of notification on syntax change (we may get that already?) such that we can react to the syntax changes correctly. Technically we could base the syntax on the Vim FT but that would get complicated since the Code stuff is all by extension.

We should probably also implement the `"files.associations"` option from VSCode, such that you can add permanent associations between extensions and syntax highlights.

**Comment by CrossR** [comment]
Going to close this out in favour of the more general #782.
