### ISSUE TITLE
OSX - No Command+Shift+P?

### ISSUE THREAD

**Issue by docwhat** [onivim/oni2#520]
I use Dvorak keyboard on OSX 10.14.6

- Command+P and Command+Shift+P enter insert mode.  (I'm physically pressing <kbd>R</kbd> for the Dvorak key "P").
- Control+L enters the fuzzy file finder. (I'm physically pressing <kbd>P</kbd> for the the Dvorak key "L").
    - This crashes pretty quick.  I think there is a bug already for this.
- Control+Shift+L enters the command pallet. (I'm physically pressing <kbd>P</kbd>).
    - Nothing I select with the <kbd>return</kbd> key works.

**Comment by danieljamespost** [comment]
I am using Colemak and experiencing this issue as well. If there is a way to enable debug mode in the release build, I'm happy to send over a stack trace.

**Comment by jcorbin** [comment]
+1 to this: I have to press physical "Cmd+Shift+P" to get the palette as a dvorak user; the keybind doesn't seem to respect mac os's keymap. This isn't terribly surprising fwiw, since many games have similar problems; so it's likely that revery et al just doesn't get this right yet.

The next step down this road is "only honors keymap present at application start". This is another bug that some game have: start in dvoark, always use dvorak mapped binds (likewise for qwerty); swapping doesn't pick up. This is especially insidious if:
- you've got a hardware dvorak keyboard
- and you also unplug, and then need to swap to the software-remapped notebook builtin keyboard

This is a less common event for games, but frequent for something that I leave running all day, like "my editor" ;-)

**Comment by bryphe** [comment]
I believe the move to SDL2 will help us more precisely handling these layouts: https://github.com/onivim/oni2/pull/780 , and seems to handle the switching-layout-while-running case as well.

**Comment by jcorbin** [comment]
Works For Me Now ™

**Comment by bryphe** [comment]
Awesome! Thanks for the confirmation @jcorbin . 

I'll close this out, but please feel free to log a new issue if there are still input-layout cases that are not working as expected. Still seem to be some remaining issues in #557 in particular I'm tracking
