### ISSUE TITLE
control-<key> sends scancode not keycode

### ISSUE THREAD

**Issue by ntgraff** [onivim/oni2#522]
I use a non-qwerty keyboard layout, and when not pressing control the keys send as expected, but when control is pressed it sends the scancode, not the keycode. For example if I press `<c-p>` it will send `<c-r>` when using dvorak.

**Comment by ntgraff** [comment]
If I could get a pointer to where the code to fix this is I could try to work on it. This is blocking any use of the editor for me, as any key with control is broken. I would also petition to change the tag from enhancement to bug and/or daily editor blocker, because that is what it is.

**Comment by CrossR** [comment]
There is some input changes going on in the background around SDL to my knowledge, which may help in this area. There is talks over in discord about that.

**Comment by jcorbin** [comment]
Related to #520 and #557

**Comment by bryphe** [comment]
Hi @jcorbin and @ntgraff ,

This _should_ be fixed in the latest builds - we now use SDL2 and pick up virtual key codes. I've tested Dvorak on Windows, OSX, and Arch Linux, and it seems to work as expected. 

Would you be up for trying the latest and let me know if to works for you?

If not - let me know which platform you're using and I'll continue to investigate 👍

**Comment by ntgraff** [comment]
Seems to work as expected!

**Comment by bryphe** [comment]
Great news! Thanks for checking, @ntgraff !
