### ISSUE TITLE
Oni2 cannot copy default config to user folder

### ISSUE THREAD

**Issue by Raikiri** [onivim/oni2#524]
When I launch Oni2.exe under windows with -f, it gives me this log:
![image](https://user-images.githubusercontent.com/1657728/62253708-e1c6ea00-b44a-11e9-804d-dbc2ff4848a8.png)
Once I copy configuration.json manually from Oni2 folder to AppData/Local/Oni2, it no longer complains.

**Comment by CrossR** [comment]
I think both this and #525 will be fixed if we go ahead with https://github.com/onivim/oni2/issues/356.

That is, if we generate the config, we won't need to copy it, and the generated config should also be valid JSON since we will have generated it.

I'll leave them both open since they are useful and more easily found when more people come to raise this same issue though, since https://github.com/onivim/oni2/issues/356 doesn't really look like its related at first. When https://github.com/onivim/oni2/issues/356 is complete though, we should be able to close both of these issues.
