### ISSUE TITLE
AltGr key combinations doesn't work

### ISSUE THREAD

**Issue by rehnarama** [onivim/oni2#544]
# Problem
In some keyboard languages (e.g. swedish, sv) you use AltGr key combinations to insert certain special characters, e.g. `@£$€{[]}\´`.

In onivim2, in insert mode, or in the command line, I can't seem to enter these characters. Instead, garbled text/characters is inserted in it's place.
## How to Reproduce
On a swedish keyboard layout, try to enter any AltGr combination, e.g. press `AltGr+2` to try to enter an `@` character, and note the garbled text.
## Observed Behaviour
The garbled text looks like this when trying to insert an `@` character
![bild](https://user-images.githubusercontent.com/1352555/62316547-06957e80-b498-11e9-94ad-c46952e49ec8.png)

## Expected Behvaiour
I'd expect an `@` character to be inserted in the garbled text's place.

# Note
In the command palette and fuzzy file finder, inserting these AltGr shortcuts works as expected.
![bild](https://user-images.githubusercontent.com/1352555/62316663-4492a280-b498-11e9-99a8-4191f453c1bd.png)

# Version
```
    Version: 2.0.2.0
    Date: 2019-08-01 07:04:21
    Commit: f98f448
```
OS: Windows 10

**Comment by brouer** [comment]
This issue should, IMHO, have the "daily editor blocker" label.

**Comment by CrossR** [comment]
I've updated the labels, and we should probably add a general "Moving to SDL2" issue, to collate the things that move will help us with. It should help with input issues, but I don't know specifically about which ones.

From the fact that we deal with this fine in one place and badly in another, I expect this issue is more related in the passing or parsing to `libvim`, rather than an input issue itself, such that the move away from GLFW won't especially help.

**Comment by nolondil** [comment]
Last build seems to have solved this issue.

**Comment by bryphe** [comment]
Excellent, thanks for confirming, @nolondil ! Our switch to SDL2 should address the AltGr / keyboard layout issues now 👍  

I'll close this out, but let me know if anyone is still seeing issues with the latest.
