### ISSUE TITLE
Commands: QuickOpen - open in vertical split / open in horizontal split

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#564]
For the QuickOpen, it is often convenient to be able to open directly in a split.

We should have shortcut keys out-of-the-box for this, as well as have them be bindable commands.

Proposal:
- `quickOpen.verticalSplit` - opens the currently selected file in a vertical split (Default: `<c-v>`)
- `quickOpen.horizontalSplit` - opens the currently selected file in a horizontal split (Default: `<c-s>`)

These commands would only be enabled when the quickopen menu is up

**Comment by mhanberg** [comment]
I would suggest making the default horizontal split be `<c-x>`. 

This is the default command that is used by fzf.vim and ctrlp.vim

However, the command-t vim plugin uses `<c-s>`, so i'll admit that it is subjective.

VSCode currently uses `<c-enter>` to do a vertical split (I don't know if it's possible to do a horizontal split).

**Comment by KevinSjoberg** [comment]
As an avid Vim user myself, I find `<c-s>` and `<c-v>` familiar since `<c-w s>` and `<c-w v>` split and vertically split respectively in vim. I'll have to admit that `<c-x>` and `<c-v>` is pretty much muscle memory at this point as well since I'm using FZF on a daily basis.

If I had to vote, I'd go with `<c-s` and `<c-v>`.

**Comment by KevinSjoberg** [comment]
I'm up for giving this a shot. 🙂

**Comment by KevinSjoberg** [comment]
@bryphe looking through the code I believe we don't distinguish between what kind of menu is being open. It looks like we're using `MenuOpen` and depending on what command triggered it, we populate the contents accordingly. Is that right?

If that's the case, I thought it might be a good idea talking a bit about how we move forward. Since we're about to add bindable commands for opening a given file in a split, I can see a use case for adding the ability to determine what type of menu is currently open.

We could either extend `MenuOpen(menuCreator)` with another constructor argument such as `MenuOpen(menuType, menuCreator)` or separate them altogether.

What are your thoughts?
