### ISSUE TITLE
Slow performance on directories with many files/folders

### ISSUE THREAD

**Issue by null-dev** [onivim/oni2#602]
Steps to reproduce:
1. Create a directory with many files/folders (e.g. in Bash: `for i in {1..10000}; do mkdir "$i"; done;`)
2. Open Onivim in the folder

**Comment by bryphe** [comment]
Thanks for the issue, @null-dev .

I think there are two relevant pieces here:
- __Startup Performance:__ We had issues where the startup time would increase due to populating the file explorer: https://github.com/onivim/oni2/pull/320 We should, at the very least, make this traversal asynchronous.
- __Runtime Performance:__ The file explorer isn't _virtualized_ - so for a large folder, we end up rendering every file/folder in the tree!
