### ISSUE TITLE
+ register in normal mode pastes in the new line

### ISSUE THREAD

**Issue by pkariz** [onivim/oni2#660]
whenever i do "+p it pastes the result in the new line. Eg. if i have 'bla' in the clipboard and have file:
```
line[1]
line2
```
where `[x]` indicates cursor position in normal mode and i do "+p then i get:
```
line1
[b]la
line2
```
instead of:
```
line1bl[a]
line2
```
It works fine in the insert mode with Ctrl+v.

**Comment by bryphe** [comment]
Ah, good catch - thanks @pkariz for logging the bug!

I believe this is because we are always defaulting to the `MLINE` yank register type: https://github.com/onivim/libvim/blob/2eff31df7b8384a93c90222f39140673b3680a75/src/ops.c#L783

I guess, for a single line, perhaps we should be pasting in character mode / `MCHAR`
