### ISSUE TITLE
⌘+⇧+p Fuzzy-finder is case-sensitive

### ISSUE THREAD

**Issue by Spirarel** [onivim/oni2#691]
## What?
When searching the command palette the current results of the fuzzy finder are case-sensitive, yielding unexpected behavior where, as you complete a word, the correct match disappears.
## Example
**Correct casing**
<img width="406" alt="Screen Shot 2019-08-24 at 11 22 44" src="https://user-images.githubusercontent.com/10119394/63640066-9f678600-c661-11e9-9398-4c3a87781fca.png">
**Somewhat matching initial segment (wrong-case)**
<img width="404" alt="Screen Shot 2019-08-24 at 11 23 08" src="https://user-images.githubusercontent.com/10119394/63640072-a68e9400-c661-11e9-9fe5-55795a20a6a2.png">
**False-negative initial segment (wrong case)**
<img width="406" alt="Screen Shot 2019-08-24 at 11 22 56" src="https://user-images.githubusercontent.com/10119394/63640074-a7bfc100-c661-11e9-8c31-59c6a61c5c2e.png">

## Environment
Onivim v0.2.0
macOS 10.14.6

## Comments
I don't know if this is considered a feature. From a new-user UX standpoint I find it counter-intuitive. For a comparison, VSC searches the command palette in a case-insensitive manner.

**Comment by CrossR** [comment]
I think this is a conflict between the initial filtering we do and the ranking.

The initial one is based on the full label (ie category + name), whereas `Filter.re` which we use for the more complex ranking is based on just the name. So we filter down to the right thing, but then the secondary filter is then using a different input.

Similarly, the secondary filter does a check for smart case (ie is the input all lower case? Do a case insensitive search, otherwise not), whereas I think the earlier filter does not.
