### ISSUE TITLE
Set default editor size

### ISSUE THREAD

**Issue by areinmeyer** [onivim/oni2#703]
Loving the editor so far! 

One thing I always do when I open oni2 is make the editor window larger.  I don't see any documentation on configuring this in the preferences.  Is this possible to set somewhere?  If so, I'll gladly update the documentation.  

If not, is this something on the roadmap?  If it's a good first issue, I might be willing to give that a shot too, though I'm pretty new to Reason.

**Comment by CrossR** [comment]
Don't think this is anywhere on the roadmap, so thanks for raising!

Think this includes a few separate parts:

 - Config options for Oni2 : We need to add some options for the default editor size, which would be just a config option to set a width and height option here : https://github.com/onivim/oni2/blob/644416a11d933f85bfaf649fbf752e3397e68828/src/editor/bin_editor/Oni2_editor.re#L30-L34. The complication may be there that I expect that is too early in the launch process for the configuration file to have been loaded.

 - Updating `revery` to have a way of saving / loading the last used editor size and other preferences (maximised, full screen, position etc), such that we can use that here as well.

The Oni2 side is probably a pretty small change, though we might need to have a little think about how the config will be loaded there. If we can avoid it, it would be better to launch with the correct size, rather than doing a resize later since that looks jarring to have that flash and rescale.

**Comment by janvanveldhuizen** [comment]
The editor is fairly small by default. So first thing I do is maximizing the window. I need to do that with my mouse, as the standard windows keys (Alt-Space)  do not seem to work :-(

**Comment by glennsl** [comment]
Should this be considered fixed by #1703? I'm not sure a setting that would only be used the first time a workspace is opened is worth the added complexity.

**Comment by janvanveldhuizen** [comment]
Yes. A lot of the pain is taken away by  reopening the editor in the previous state.

**Comment by glennsl** [comment]
Closing this as it seems to have been obsoleted by workspace persistence. If anyone disagrees and would still like this, please chime in.
