### ISSUE TITLE
filetype php

### ISSUE THREAD

**Issue by tofulm** [onivim/oni2#707]
When I open a file .php with the last onivim2.appimage on linux ([7676fc5](https://github.com/onivim/oni2/commit/7676fc509955ebe40452b349bf229e792c2fe37f))
the filetype is not recognized.
When I try `:set filetype=php` It doesn't work any better.

**Comment by CrossR** [comment]
We currently don't ship with any PHP syntax highlights, you can see the ones we do have over in https://github.com/onivim/oni2/tree/master/extensions.

A PR to add this should just be copying the extensions over from VSCode (#171, #636). That said, we are also looking at moving to `tree-sitter` powered syntax highlights as well, and PHP looks to have `tree-sitter` definitions, so we could use them in the future instead of the `textmate` ones.

We should probably raise a seperate issue to hook up `set ft`, since currently it doesn't do anything on the Oni side, where we'd rather send over a notification to Oni or something.

**Comment by tofulm** [comment]
thanks

**Comment by costra** [comment]
Why this enhancement was closed? I'm voting for PHP support, please!

**Comment by CrossR** [comment]
I expect they installed it themselves locally!

I'll stick a PR in now for PHP, and if anyone else is wondering what the steps are it is as follows:

 - `git clone` VSCode
 - `cp -r vscode/extensions/LANG ~/git/oni2/extensions/`
 - Run Oni2 and just have a quick check with a test file.

Or, if its something more niche you think not worth commiting to the main repo, just copy to your extensions folder - https://onivim.github.io/docs/configuration/extensions#installing-extensions
