### ISSUE TITLE
Closing window with unsaved changes results in no other window being created for new buffers

### ISSUE THREAD

**Issue by avimmer** [onivim/oni2#733]
Related to #610 

Version: 2.0.2.0
Date: 8/31/2019, 5:18:41 AM
Commit: 237e14b

* Start onivim2
* Observe there's a new untitled buffer open
* Enter insert mode
* Type "test"
* Observe window close button change to a modified buffer indicator
* Press the modified buffer indicator
* Window closes and you're presented with an empty pane
* Try opening any other buffer using file explorer or command
* Observe new buffers being opened as indicated by the status line, but no actual window appears until restart. It feels like you can modify those buffers without any visual feedback.

**Comment by bryphe** [comment]
Nice catch @avimmer ! Definitely a bug - we end up in a broken state where buffers aren't being opened.

**Comment by leavengood** [comment]
This can still happen with the Welcome pane too. Steps now:

1. Start onivim2
2. Use `:e some_new_file.txt` to get a new file.
3. Close the Welcome tab.
4. Make some changes in the new file.
5. Click the modified circle to close the new file.
6. Bad state now entered.

I believe an empty window should be a valid state in general, because we probably need a checkbox on the welcome screen to be able to turn it off, like in VSCode. In fact, now that I test VSCode, their empty window has something sort of like the current onivim2 welcome tab:

<img width="693" alt="Screen Shot 2020-03-11 at 5 11 39 PM" src="https://user-images.githubusercontent.com/637/76464254-66072580-63bb-11ea-8477-01dc74a6b285.png">


So obviously we need a bit more work there, but it is probably not too hard. I may investigate some of this.
