### ISSUE TITLE
Readme says "pay-what-you-want"

### ISSUE THREAD

**Issue by danielb2** [onivim/oni2#747]
but the website says $19

**Comment by gianlcl** [comment]
Readme is out of date, pay-what-you-want event is over since July 31. Now the value raised to $19.
And will raise again on Oct 31, so if you want to buy, better do it before Oct 31.
Remember that onivim2 is free to personal use, the license is for commercial use. Buying now what you gets is access to early access builds. At the bottom of the website there is a develpoment timeline.
At last I just want to say, if you can afford, buy it. Is always good to support developers. Me as one, know how hard is to do such kind of project.

**Comment by bryphe** [comment]
Sorry about that! Thanks for reporting (and thank you @gianlcl for the great answer, couldn't have said it better myself 😄 )
