### ISSUE TITLE
Question: A way to navigate command palette with vim (j,k) keys instead of arrow keys?

### ISSUE THREAD

**Issue by Mungoid** [onivim/oni2#749]
I know they are letter keys and need to be used as such, but I find using the arrow keys in the command palette throws off the 'vim' experience for me. I think it would feel more natural if there were a way to use the _j_ and _k_ keys without them typing into the palette. 

Was thinking something like if you are holding down a modifier of some sort and pressing _j_ or _k_ while the palette was open, it would allow you to move up and down. Not sure how that would impact other uses of those keys though. 

This is definitely not critical by any means. More just curious if something like that could be possible?

**Comment by CrossR** [comment]
For reference, we do have `Ctrl-p`/`Ctrl-n` bound to scroll through them, which is the default for the autocomplete etc in vim to my knowledge.

I would guess that we could use `j` `k` for this as well (with a modifier), and I would expect that you could just add that to your keybinds config file already by duplicating the existing `Ctrl-p/n` ones that are there.

That said, I feel like there might be something missing with linking up the keybinds, though I can test this as I'm away from my Windows PC at the moment and my Mac has a bunch of config things that use Ctrl-j etc already, so I've unbound them from other apps...

**Comment by jrwrigh** [comment]
I would generally say that `Ctrl-p` and `Ctrl-n` are much more standard for the "vim experience" rather than using `mod+[j/k]`. 

My two cents: leave it with `Ctrl-p` and `Ctrl-n`. This leaves `mod+[j/k]` open to do other keybindings. If users want to use `mod+[j/k]` to move through lists, then they can make it a keybinding. That might be the conclusion y'all already came to, but I couldn't quite tell.
