### ISSUE TITLE
Feature Request: let an Oni2 command that sends vimscript be writable in the keybindings file

### ISSUE THREAD

**Issue by snoblenet** [onivim/oni2#807]
Hi. Exciting project. I was happy to buy the lifetime license to support future development.
It's not yet ready for me to use for actual work so I don't have extensive feedback but I do have two big feature requests which I'm posting in two tickets. I might note some of the glitches etc I've encountered later but I'm sure you're overwhelmed with those now.

Feature Request: let an Oni2 command that sends vimscript be writable in the keybindings file

I picture myself then doing something like this:

```
{
    "bindings": [
        { "key": "<⌘-`>", "command": "sendVimscript", "args": [[":bnext"]] },
        { "key": "<S-⌘-`>", "command": "sendVimscript", "args": [[":bprev"]] },
        { "key": "<⌘-W>", "command": "sendVimscript", "args": [[":q!"]] },
    ]
}
```

**Comment by CrossR** [comment]
This sounds like it goes alongside and possibly is related to the new PR: https://github.com/onivim/oni2/pull/805

I think that this further syntax / a similar syntax is potentially useful still since I think there is some keybinds that vim can not distinguish between, that we can distinguish between at the Oni2 layer. This would allow the binds that vim can't understand to be used still.

**Comment by bryphe** [comment]
Sounds like a great idea to help merge the Oni2 <-> vim worlds!

How would you feel about a convention like:
```
"command": ":bpnext"
```

where if the command starts with a `:`, we assume that it is a VimL command?

**Comment by snoblenet** [comment]
Sounds good to me. And I presume the `<CR>` at the end of the mapping is implied without the user having to specify it specifically.
