### ISSUE TITLE
Add hidden files to quick open

### ISSUE THREAD

**Issue by CrossR** [onivim/oni2#860]
Currently the quick open (`Ctrl/Cmd - P`) doesn't show hidden files or folders (ones starting with a `.`).

To add this we need to do a few things:

 1. Add `--hidden` to the `ripgrep` flags over in `Ripgrep.re`.
 2. Hook up the config option to be passed over.
 3. Build up a bunch of `--glob=!` arguments based on the `files.exclude` configuration setting. (This might also have to include the `.git` folder, I can't remember if that is ignored by default/is included in the `files.exclude`.)

At that point we should have hidden files and excluded files being ignored from the search.

**Comment by dycu** [comment]
Adding `--hidden` flag solves the problem as you suggested. I'm struggling with adding flags from the configuration though.

If I understand correctly `Ripgrep.make` runs the job separated from the whole `react` architecture. Because of that I have no access to the `state` and to the configuration as a result.

Is there any other way of accessing the configuration that should be used here?

**Comment by amiralies** [comment]
@glennsl can I work on this?

**Comment by glennsl** [comment]
@amiralies Yeah, absolutely. Thank you!
