### ISSUE TITLE
Bug - CJK - Default font does not support CJK characters

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#868]
From twitter: https://twitter.com/KrComet/status/1185134484498206721

![image](https://user-images.githubusercontent.com/13532591/67129721-3fe6ac00-f1b4-11e9-8c15-0906531d3ad0.png)

Our current font (FiraCode) doesn't support CJK characters out-of-the-box.

Test file:
[cjk.txt](https://github.com/onivim/oni2/files/3745752/cjk.txt)

A workaround is to use a font that supports monospace characters, like the 'Mono' variants here: https://github.com/googlefonts/noto-cjk (however, we still have the same issue here - where the font widths aren't correct: https://github.com/onivim/oni2/issues/765)

But we should have fallback fonts set up for this case, too.

**Comment by kexplorning** [comment]
Maybe... have a look at this font: [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic).

> This is SARASA GOTHIC, a CJK programming font based on Iosevka and Source Han Sans.

Just a suggestion...

**Comment by zbaylin** [comment]
@bryphe I think we can close this now since the merging of #2113 - the default font still doesnt contain CJK glyphs but since we have fallback that shouldn't really matter, I don't think.

I've tested CJK characters, as you can see on [my blog post about implementing fallback](https://zachbayl.in/blog/font-fallback-revery.html), so I think we're good here.

Please reopen if you think I'm incorrect!
