### ISSUE TITLE
Bug - `relativenumber` stopped working properly

### ISSUE THREAD

**Issue by awilkins** [onivim/oni2#888]
I quite liked the default of `relativenumber`, although I get that people new to Vim find this confusing.

Now it renders a layout like `relativenumber` (with the offset absolute line number on the current line), but the indented numbers are absolute line numbers, not relative.

Issuing a `relativenumber` or `number` command doesn't do anything - it continues to render as above.

**Comment by paskausks** [comment]
I'm currently using hybrid numbers in vim and VSCode (`set rnu nu`). Would be great to get this functionality in Oni2 as well!

**Comment by CrossR** [comment]
As far as I know, the Oni2 behaviour is the same as Vim when set with `set rnu nu`. I don't use `"relative"` normally, so I'm not 100% sure what the issue is?

From my brief understanding you have the current line number for the current line, and then relative everywhere else, which I think is the case in Oni2 as well?

![image](https://user-images.githubusercontent.com/10038688/67436750-16c88000-f5e7-11e9-85a2-601edb57ba68.png)

In both the current line is 8 and every other line is the count of the distance from the current line.

(Note this is opt in, I think the default is just `"on"` : https://onivim.github.io/docs/using-onivim/configuration#editor)

**Comment by paskausks** [comment]
@CrossR yeah, setting `"editor.lineNumbers": "relative"` did what i was looking for. Thanks! Hope that answer's @awilkins question too.
