### ISSUE TITLE
Add screen recordings for new PR (aka Demo)

### ISSUE THREAD

**Issue by fanantoxa** [onivim/oni2#913]
## Domain knowledge
* PRs can update or add new UI features
* PRs can update or add new editor commands, etc.. (editing features)
* once feature implemented it usually coming testing (manual) to check that everything works as expected

## Idea
* Maybe would make screen recording during final test (aka Demo)
  (It many tools for any platform that allow make easy and fast screen(part of screen) recording and save it as gif)
* Attach it as GIF to PR

## Benefit 
* Users that have early access will know what was added
* They can use it right away and provide some additional testing
* Don't need to look up in code and try to understand what is the feature

**Comment by paskausks** [comment]
I'm trying to keep track with the development of oni2, since the project is quite interesting to me,as I feel like Oni2 would perfectly fill the gap between TUI vim and VSCode as a compromise between appearance and performance, but going over the notifications (I'm watching the repo) does takes considerable time if I wan't to keep up with the developments.

But, while screen recordings for feature PRs would a great feature, I think this would accumulate in quite an overhead to the overall development, even if streamlined, and I'd rather have the guys building Oni2 focus the time on, well, building the thing (the alpha release was already postponed from end of October to end of the year IIRC).

This was a rather long intro to say that I'd as much appreciate just a weekly (may be even bi-weekly or monthly) email, even though i could just as well go to the home page and check out the weekly changelist.

**Comment by fanantoxa** [comment]
@paskausks From GTD perspective make more sense to make a record right away.
You not loosing context, you just did a thing so making it one more time will take much less time then trying to remember all thing you did for a week. 
Also development speed quite fast and it a lot of features for a week.
In addition from my experience making screen recording take about 3-5 minutes. 
I just open software, select part of screen that I need to record and click start. Once I finished I click stop and I have nice demo video.

Also this videos might help to make a help documentation later.
But still it up to developer and how it work for them.

**Comment by bryphe** [comment]
We now have the [N-screenshot](https://github.com/onivim/oni2/pulls?q=is%3Aopen+is%3Apr+label%3AN-screenshot) label which i use to tag PRs
