### ISSUE TITLE
Is line-height option supported?

### ISSUE THREAD

**Issue by smorimoto** [onivim/oni2#966]

**Comment by lessp** [comment]
Where would one start to look for this?

**Comment by glennsl** [comment]
It's a field in the `Draw.context` used in the editor component:

https://github.com/onivim/oni2/blob/d61477c402d72a53e536418cb2e007739956e7a4/src/Feature/Editor/Draw.re#L16

The draw context for the surface is created here, where it's just hard-coded to the font height:

https://github.com/onivim/oni2/blob/d61477c402d72a53e536418cb2e007739956e7a4/src/Feature/Editor/SurfaceView.re#L136-L145

So it would have to be passed in as prop to the component, which is then wired up to a configuration setting.

**Comment by lessp** [comment]
Thanks! I actually started doing some digging myself, and thought about following:

https://github.com/onivim/oni2/blob/97d122c9bedfbe350639ccc5173cde18319c9ac6/src/Service/Font/FontLoader.re

https://github.com/onivim/oni2/blob/97d122c9bedfbe350639ccc5173cde18319c9ac6/src/Service/Font/Service_Font.re

... and adding it to the configurations

But if I understand you correctly, one might not even have to go there, but rather the largest portion of work would kind of be adding it to the configuration settings. Might have to take a look at it during the weekend!

**Comment by glennsl** [comment]
Yeah, no need for a service. Just a configuration setting that's passed on.

Thanks for looking into this @lessp!

**Comment by DanielPower** [comment]
@lessp wondering if you started looking into this after? I was planning to do this myself until I saw your response, wouldn't want to duplicate your work.

**Comment by lessp** [comment]
> @lessp wondering if you started looking into this after? I was planning to do this myself until I saw your response, wouldn't want to duplicate your work.

Hey @DanielPower, I had planned to look at it this weekend, but never came around to it. No hard feelings if you'd like to take a stab at  it instead, I won't be able to look at it until next weekend anyway, so if you have more time on your hands now, might even be done before that. 🙂

**Comment by DanielPower** [comment]
I have a WIP branch that adds the configuration option. Just dealing with some alignment issues. Aiming to finish it up tonight and put up a PR. Thank you for the link, that thread was useful.

**Comment by DanielPower** [comment]
I made some progress on the feature. Which can be found in my fork [here](https://github.com/DanielPower/oni2/tree/add-line-height-configuration). I unfortunately had less time than I had hoped over the week, and this is also my first time using Reason, so I spent some of that time just figuring out the syntax.

@lessp if you'd still like to pick this up over the weekend, you're more than welcome to use my branch as a starting point. If not, I'll continue if I can find the time.

The current status is: The configuration setting is there, and both text and line numbers align correctly. But there are a few issues.

I wasn't able to figure out how to pass the configuration value into the editor. It seems that the font is passed in as an argument when the editor is created, and there's some sort of event system that calls editor.setFont when the font changes. I'm guessing something similar would need to be done for lineHeight.

The config isn't currently accessible in places where the editor is initialized, or at least, I couldn't figure out how to read from it, other than in SurfaceView.re. Because of this, I currently have lineHeight hardcoded to `2.0` when editor is created, just to test that the `getLineHeight` function work.

The only other thing I've noticed is that whitespace characters do not align correctly. I didn't really look into where they're rendered yet, because I was more focused on getting the configuration value into the editor.
